import { ArrowLeft, ArrowRight, Check, GitBranch, Link2, LockKeyhole, RotateCcw, Send, ShieldCheck, Unlink, X } from "lucide-react";
import { useState } from "react";
import { Link, useLocation } from "react-router-dom";
import { selectionTrace, TRACE_CHAINS } from "../../domain/expansion";
import { APPLICANTS, GIGS, QA, TERMS } from "../../domain/fixtures";
import type { Role, ViewId } from "../../domain/types";
import { useConceptRoute } from "../../domain/useConceptRoute";
import "./trace.css";

export function Trace(){const location=useLocation();const route=useConceptRoute("trace");if(location.pathname==="/trace"||location.pathname==="/trace/")return <Landing/>;return <TraceApp {...route}/>}

function Landing(){return <main id="main-content" className="tr-public"><header><Link to="/">15 / INDEX</Link><b>TRACE</b><span>GIGMATCH AI · SOURCE → CLAIM → CONSEQUENCE</span></header><section><div><span>EVERY DECISION HAS AN ORIGIN</span><h1>Follow the claim<br/>back to <em>proof.</em></h1><p>Trace recommendations, proposal versions, exact authority, and contact permission without decorative graphs or hidden reasoning.</p><nav><Link to="/trace/freelancer/home">Trace specialist journey <ArrowRight/></Link><Link to="/trace/client/home">Trace client decision <ArrowRight/></Link></nav></div><aside>{TRACE_CHAINS.map((item,index)=><div key={item.id}><span>0{index+1}</span><p><small>SOURCE</small><b>{item.source}</b></p><i/><p><small>CLAIM</small><b>{item.claim}</b></p><i/><p className={item.id==="gap"?"is-gap":""}><small>CONSEQUENCE</small><b>{item.consequence}</b></p></div>)}</aside></section></main>}

interface Props{role:Role;view:ViewId;go:(view:ViewId)=>void;switchRole:(role:Role)=>void;state:ReturnType<typeof useConceptRoute>["state"];dispatch:ReturnType<typeof useConceptRoute>["dispatch"]}

function TraceApp({role,view,go,switchRole,state,dispatch}:Props){
  const nav:{v:ViewId;f:string;c:string}[]=[{v:"home",f:"Origins",c:"Origins"},{v:role==="client"?"review":"discover",f:"Recommendations",c:"Applicants"},{v:role==="client"?"candidate":"applications",f:"My chain",c:"Candidate chain"},{v:"selection",f:"Authority chain",c:"Authority chain"},{v:"engagement",f:"Engagement chain",c:"Engagement chain"}];
  return <div className="tr-app"><header className="tr-header"><Link to="/trace"><GitBranch/>TRACE <small>15</small></Link><nav>{nav.map(item=><button className={view===item.v?"is-active":""} key={item.v} onClick={()=>go(item.v)}>{role==="client"?item.c:item.f}</button>)}</nav><div><button className={role==="freelancer"?"is-active":""} onClick={()=>switchRole("freelancer")}>SPECIALIST</button><button className={role==="client"?"is-active":""} onClick={()=>switchRole("client")}>CLIENT</button></div></header><main id="main-content">
    {view==="home"&&<Home role={role} go={go} state={state}/>}
    {view==="discover"&&<Discover go={go}/>}
    {view==="gig"&&<Gig go={go}/>}
    {view==="proposal"&&<Proposal go={go} state={state} dispatch={dispatch}/>}
    {view==="applications"&&<Application go={go} state={state} dispatch={dispatch}/>}
    {view==="review"&&<Review go={go} state={state}/>}
    {view==="candidate"&&<Candidate go={go} state={state} dispatch={dispatch}/>}
    {view==="selection"&&<Selection role={role} go={go} state={state} dispatch={dispatch}/>}
    {view==="engagement"&&<Engagement state={state} dispatch={dispatch}/>}
  </main><footer className="tr-footer"><Link to="/"><ArrowLeft/> Fifteen concepts</Link><span>TH–042 · SOURCE RECORDS PRESERVED</span><button onClick={()=>dispatch({type:"reset"})}><RotateCcw/> Reset trace</button></footer>{state.toast&&<div className="tr-toast" role="status"><Link2/>{state.toast}</div>}</div>
}

function Path({items}:{items:{label:string;value:string;state?:string}[]}){
  const[selected,setSelected]=useState<number|null>(null);
  return <div className="tr-path-wrap"><div className="tr-path">{items.map((item,index)=><div key={`${item.label}-${index}`} className={`is-${item.state??"source"}`}><button type="button" aria-pressed={selected===index} onClick={()=>setSelected(current=>current===index?null:index)}><span>{item.label}</span><b>{item.value}</b></button>{index<items.length-1&&<i><ArrowRight/></i>}</div>)}</div>{selected!==null&&<aside className="tr-inspector" role="status"><span>SOURCE INSPECTOR / NODE 0{selected+1}</span><b>{items[selected].label}</b><p>{items[selected].value}</p><small>This value remains attributable to its displayed record and version.</small></aside>}</div>
}

function Home({role,go,state}:Pick<Props,"role"|"go"|"state">){const path=selectionTrace(state.applicationVersion,state.selectionStatus);return <section className="tr-home"><header><span>ACTIVE PROVENANCE / TH–042</span><h1>{role==="client"?"The decision is only as strong as its chain.":"See exactly why this request reached you."}</h1><p>Each node exposes a source record and the consequence it authorizes.</p></header><Path items={path.map(item=>({label:item.label,value:item.value,state:item.state}))}/><div className="tr-next"><span>UNRESOLVED CONSEQUENCE</span><b>{state.selectionStatus==="pending"?"Kavya can accept application v"+state.applicationVersion:"Client must renew exact authority"}</b><button onClick={()=>go("selection")}>Inspect authority chain <ArrowRight/></button></div></section>}

function Discover({go}:Pick<Props,"go">){const[selected,setSelected]=useState(0);const gig=GIGS[selected];return <section className="tr-discover"><header><span>RECOMMENDATION PROVENANCE</span><h1>Why this brief appears here.</h1></header><nav>{GIGS.map((item,index)=><button className={selected===index?"is-active":""} key={item.id} onClick={()=>setSelected(index)}><strong>{item.match}</strong><span><b>{item.company}</b><small>{item.title}</small></span></button>)}</nav><Path items={[{label:"Required capabilities",value:gig.requiredSkills.join(" · ")},{label:"Reviewed evidence",value:gig.matchingSkills.slice(0,4).join(" · ")},{label:"Recommendation",value:`${gig.match} / ${gig.matchLabel}`,state:"effective"}]}/><div className="tr-gap"><X/><span>TRACE TERMINATES</span><b>{gig.missingSkills[0]}</b><p>No evidence is inferred or substituted.</p></div><button className="tr-primary" onClick={()=>go("gig")}>Open complete source chain <ArrowRight/></button></section>}

function Gig({go}:Pick<Props,"go">){const gig=GIGS[0];return <section className="tr-gig"><header><button onClick={()=>go("discover")}><ArrowLeft/> Recommendations</button><span>BRIEF PROVENANCE / GIG TERMS v3</span><h1>{gig.title}</h1><p>{gig.summary}</p></header><div className="tr-requirements">{TRACE_CHAINS.map(item=><Path key={item.id} items={[{label:"Source",value:item.source},{label:"Requirement",value:item.claim},{label:"Reviewed record",value:item.evidence,state:item.id==="gap"?"broken":"source"},{label:"Result",value:item.consequence,state:item.id==="gap"?"gap":"effective"}]}/>)}</div><div className="tr-material"><span>MATERIAL TERMS ORIGIN / GIG v3</span><b>{gig.budget}</b><b>{gig.duration}</b><b>{gig.commitment}</b><button onClick={()=>go("proposal")}>Create proposal branch <GitBranch/></button></div></section>}

function Proposal({go,state,dispatch}:Pick<Props,"go"|"state"|"dispatch">){const[note,setNote]=useState("");const invalid=note.length<24;return <section className="tr-proposal"><header><span>NEW PROPOSAL BRANCH / FROM APPLICATION v{state.applicationVersion}</span><h1>A change must show what it breaks.</h1></header><div className="tr-branch-preview"><Path items={[{label:"Gig terms",value:"v3"},{label:"Current application",value:`v${state.applicationVersion}`},{label:"Selection",value:state.selectionStatus,state:state.selectionStatus==="pending"?"effective":"source"}]}/><div className="tr-break"><Unlink/><b>RECORDING v{state.applicationVersion+1} BREAKS THIS SELECTION LINK</b></div></div><form onSubmit={event=>{event.preventDefault();if(!invalid){dispatch({type:"submit-revision"});go("applications")}}}><label>FIXED PROPOSAL<input defaultValue="₹5,80,000"/></label><label>DELIVERY<input defaultValue="14 weeks"/></label><label>CAPACITY<input defaultValue="28 hours/week"/></label><label>CHANGE SOURCE<textarea value={note} onChange={event=>setNote(event.target.value)} placeholder="Explain why this version exists."/>{invalid&&<small role="alert">Add at least 24 characters.</small>}</label><button disabled={invalid}>Create branch v{state.applicationVersion+1} <Send/></button></form></section>}

function Application({go,state,dispatch}:Pick<Props,"go"|"state"|"dispatch">){return <section className="tr-application"><header><span>APPLICATION LINEAGE / AP.001</span><h1>Every version remains attributable.</h1></header><Path items={[{label:"Gig terms",value:"v3"},{label:"Application",value:`v${state.applicationVersion}`},{label:"Stage",value:state.applicationStage,state:"effective"},{label:"Selection",value:state.selectionStatus,state:state.selectionStatus==="invalidated"?"broken":"effective"}]}/><div className="tr-record-sources"><section><span>COMMERCIAL SOURCE / APPLICATION v{state.applicationVersion}</span><strong>{TERMS.proposal}</strong><p>{TERMS.timeline} · {TERMS.availability}</p><button onClick={()=>go("proposal")}>Branch proposal</button></section><section><span>Q&A SOURCE / IMMUTABLE</span><blockquote>{QA.question}</blockquote>{state.qaAnswered?<p>{QA.answer}</p>:<button onClick={()=>dispatch({type:"answer-qa"})}>Record attributable answer</button>}</section></div>{state.selectionStatus==="pending"&&<button className="tr-primary" onClick={()=>go("selection")}>Inspect authority lineage <ArrowRight/></button>}</section>}

function Review({go,state}:Pick<Props,"go"|"state">){const[selected,setSelected]=useState(0);const person=APPLICANTS[selected];return <section className="tr-review"><header><span>CLIENT REVIEW / SOURCE INSPECTOR</span><h1>Compare the claim by following its origin.</h1></header><div className="tr-review-grid"><nav>{APPLICANTS.map((item,index)=><button className={index===selected?"is-active":""} key={item.id} onClick={()=>setSelected(index)}><strong>{item.match}</strong><b>{item.name}</b><small>{item.id==="kavya"?state.applicationStage:item.stage}</small></button>)}</nav><section><span>SELECTED LINEAGE / {person.id}</span>{person.skills.slice(0,4).map(skill=><Path key={skill} items={[{label:"Brief v3",value:`${skill} required`},{label:"Applicant record",value:`${skill} evidence`},{label:"Review result",value:"Covered",state:"effective"}]}/>)}<div className="tr-gap"><X/><span>DISCLOSED GAP</span><b>{person.gap}</b></div><button onClick={()=>go("candidate")}>Open complete candidate trace <ArrowRight/></button></section></div></section>}

function Candidate({go,state,dispatch}:Pick<Props,"go"|"state"|"dispatch">){const person=APPLICANTS[0];return <section className="tr-candidate"><header><button onClick={()=>go("review")}><ArrowLeft/> Applicant traces</button><span>CANDIDATE LINEAGE / AP.001 / v{state.applicationVersion}</span><h1>{person.name}</h1><p>{person.headline}</p></header><div className="tr-candidate-paths"><Path items={[{label:"Reviewed artifacts",value:person.skills.join(" · ")},{label:"Evidence result",value:"92 / Strong",state:"effective"},{label:"Client decision",value:state.advanced?"Advanced":"Under review",state:"effective"}]}/><Path items={[{label:"Application v"+state.applicationVersion,value:person.proposal},{label:"Commercial terms",value:person.timeline+" · "+person.availability},{label:"Suitability",value:"Not influenced by price",state:"source"}]}/><Path items={[{label:"Applicant disclosure",value:person.gap},{label:"Review treatment",value:"Gap preserved",state:"gap"}]}/></div><footer><button className={state.shortlisted?"is-active":""} onClick={()=>dispatch({type:"toggle-shortlist"})}>{state.shortlisted?"✓ Private shortlist":"+ Private shortlist"}</button><button onClick={()=>dispatch({type:"toggle-advance"})}>{state.advanced?"Return to review":"Advance"}</button><button onClick={()=>dispatch({type:"request-revision"})}>Request revision</button><button onClick={()=>go("selection")}>Trace selection authority <ArrowRight/></button></footer></section>}

function Selection({role,go,state,dispatch}:Pick<Props,"role"|"go"|"state"|"dispatch">){const[deadline,setDeadline]=useState<"24"|"48"|"72">(state.selectionDeadline);const client=role==="client";const path=selectionTrace(state.applicationVersion,state.selectionStatus);return <section className="tr-selection"><header><span>ATOMIC AUTHORITY LINEAGE</span><h1>{state.selectionStatus==="invalidated"?"The chain is broken by design.":"Every source required for acceptance."}</h1><p>No term is inferred outside the chain shown below.</p></header><Path items={path.map(item=>({label:item.label,value:item.value,state:item.state}))}/>{state.selectionStatus==="invalidated"&&<div className="tr-broken"><Unlink/><div><b>SELECTION SOURCE NO LONGER MATCHES CURRENT APPLICATION</b><p>A fresh client request must reference v{state.applicationVersion}.</p></div></div>}{state.selectionStatus==="none"&&<div className="tr-expired"><Unlink/><div><b>AUTHORITY LINK EXPIRED OR WITHDRAWN</b><p>No participant can accept until a fresh link references application v{state.applicationVersion}.</p></div></div>}{client&&state.selectionStatus!=="pending"&&<footer><label>AUTHORITY VALID FOR<select value={deadline} onChange={event=>setDeadline(event.target.value as "24"|"48"|"72")}><option value="24">24 hours</option><option value="48">48 hours</option><option value="72">72 hours</option></select></label><button onClick={()=>dispatch({type:"send-selection",deadline})}>Create effective link <Send/></button></footer>}{!client&&state.selectionStatus==="pending"&&<footer><p>31 hours remain. Acceptance consumes this exact authority once.</p><button onClick={()=>{dispatch({type:"accept-selection"});go("engagement")}}>Accept sourced terms <Check/></button></footer>}{state.selectionStatus==="accepted"&&<footer><p>Engagement provenance created.</p><button onClick={()=>go("engagement")}>Open engagement trace <ArrowRight/></button></footer>}</section>}

function Engagement({state,dispatch}:Pick<Props,"state"|"dispatch">){const contactState=!state.contactShared||state.contactRevoked?"No consent":state.contactRevealed?"Displayed":"Masked share";return <section className="tr-engagement"><header><span>ENGAGEMENT PROVENANCE / EN.001</span><h1>Shared work with an inspectable origin.</h1><p>{state.engagementStatus.replaceAll("_"," ")} · application v{state.applicationVersion} × gig v3</p></header><Path items={[{label:"Gig terms",value:"v3"},{label:"Accepted application",value:`v${state.applicationVersion}`},{label:"Atomic acceptance",value:"Recorded",state:"effective"},{label:"Engagement",value:state.engagementStatus,state:"effective"}]}/><div className="tr-engagement-grid"><section><span>LIFECYCLE CONSEQUENCE</span><strong>{TERMS.proposal}</strong><p>{TERMS.timeline} · 28 hours/week</p><button onClick={()=>dispatch({type:"advance-engagement"})} disabled={state.engagementStatus==="completed"}>Advance sourced state <ArrowRight/></button></section><aside><span>CONTACT PERMISSION LINEAGE</span><Path items={[{label:"Participant consent",value:state.contactShared&&!state.contactRevoked?"Active":"Absent",state:state.contactShared&&!state.contactRevoked?"effective":"waiting"},{label:"Reveal authority",value:state.contactRevealed?"Consumed":"Waiting"},{label:"Display",value:contactState,state:state.contactRevoked?"broken":"source"}]}/>{!state.contactShared||state.contactRevoked?<button onClick={()=>dispatch({type:"share-contact"})}><LockKeyhole/> Add consent</button>:<button onClick={()=>dispatch({type:state.contactRevealed?"revoke-contact":"reveal-contact"})}>{state.contactRevealed?<><Unlink/> Revoke display</>:<><ShieldCheck/> Authorize reveal</>}</button>}</aside></div></section>}
