import { FreelancerProfile, Gig, Application, EvaluationBenchmark } from './types';

export const INITIAL_FREELANCERS: FreelancerProfile[] = [
  {
    id: 'f-101',
    full_name: 'Elena Rostova',
    title: 'Senior Full-Stack AI Engineer',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=250',
    bio: '8+ years specializing in React, TypeScript, FastAPI, and sentence-transformers for real-time vector search and deterministic NLP pipelines.',
    hourly_rate: 95,
    completed_gigs: 24,
    rating: 4.96,
    experience_years: 8,
    location: 'San Francisco, CA (UTC-7)',
    verified_status: true,
    availability: 'Immediate',
    skills: [
      { name: 'React', category: 'frontend', proficiency: 'expert', experience_years: 7, extracted_confidence: 0.98 },
      { name: 'TypeScript', category: 'frontend', proficiency: 'expert', experience_years: 6, extracted_confidence: 0.96 },
      { name: 'FastAPI', category: 'backend', proficiency: 'expert', experience_years: 5, extracted_confidence: 0.94 },
      { name: 'Python', category: 'backend', proficiency: 'expert', experience_years: 8, extracted_confidence: 0.99 },
      { name: 'PyTorch / NLP', category: 'ai_ml', proficiency: 'advanced', experience_years: 4, extracted_confidence: 0.89 },
      { name: 'PostgreSQL / Supabase', category: 'database', proficiency: 'expert', experience_years: 6, extracted_confidence: 0.92 },
      { name: 'Docker / CI/CD', category: 'devops', proficiency: 'intermediate', experience_years: 3, extracted_confidence: 0.81 },
    ],
    parsed_resume_text: `SUMMARY: Senior Full-Stack AI Developer with 8 years of experience building high-throughput web applications and semantic matching engines. Expert in Python, FastAPI, React 19, TypeScript, PyTorch, Supabase, PostgreSQL. Developed custom sentence-transformer embedding models for talent matching systems.`,
    parsed_at: '2026-07-22T14:30:00Z',
  },
  {
    id: 'f-102',
    full_name: 'Marcus Vance',
    title: 'Distributed Systems & ML Ops Engineer',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=250',
    bio: 'Specialized in microservice architectures, high-performance vector DB retrieval, Kubernetes deployment, and scalable backend infrastructure.',
    hourly_rate: 110,
    completed_gigs: 31,
    rating: 4.98,
    experience_years: 10,
    location: 'Austin, TX (UTC-5)',
    verified_status: true,
    availability: '2 weeks',
    skills: [
      { name: 'Python', category: 'backend', proficiency: 'expert', experience_years: 10, extracted_confidence: 0.99 },
      { name: 'Go', category: 'backend', proficiency: 'expert', experience_years: 6, extracted_confidence: 0.95 },
      { name: 'Docker', category: 'devops', proficiency: 'expert', experience_years: 8, extracted_confidence: 0.97 },
      { name: 'Kubernetes', category: 'devops', proficiency: 'expert', experience_years: 6, extracted_confidence: 0.93 },
      { name: 'PostgreSQL', category: 'database', proficiency: 'expert', experience_years: 9, extracted_confidence: 0.95 },
      { name: 'FastAPI', category: 'backend', proficiency: 'advanced', experience_years: 4, extracted_confidence: 0.88 },
    ],
  },
  {
    id: 'f-103',
    full_name: 'Aria Chen',
    title: 'Lead Frontend Architect & UI Systems Engineer',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=250',
    bio: 'Crafting pixel-perfect design systems, accessible React component libraries, Next.js applications, and performant state management models.',
    hourly_rate: 85,
    completed_gigs: 19,
    rating: 4.92,
    experience_years: 6,
    location: 'Seattle, WA (UTC-7)',
    verified_status: true,
    availability: 'Immediate',
    skills: [
      { name: 'React', category: 'frontend', proficiency: 'expert', experience_years: 6, extracted_confidence: 0.99 },
      { name: 'TypeScript', category: 'frontend', proficiency: 'expert', experience_years: 5, extracted_confidence: 0.97 },
      { name: 'Tailwind CSS', category: 'frontend', proficiency: 'expert', experience_years: 5, extracted_confidence: 0.98 },
      { name: 'Next.js', category: 'frontend', proficiency: 'expert', experience_years: 4, extracted_confidence: 0.94 },
      { name: 'UI/UX Design Systems', category: 'design', proficiency: 'advanced', experience_years: 5, extracted_confidence: 0.90 },
    ],
  },
  {
    id: 'f-104',
    full_name: 'David Okafor',
    title: 'Data Platform Engineer & Embedding Specialist',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=250',
    bio: 'Building automated data pipelines, pgvector search indexes, and custom NLP skill taxonomies for enterprise SaaS applications.',
    hourly_rate: 90,
    completed_gigs: 15,
    rating: 4.88,
    experience_years: 7,
    location: 'London, UK (UTC+0)',
    verified_status: true,
    availability: '1 month',
    skills: [
      { name: 'Python', category: 'backend', proficiency: 'expert', experience_years: 7, extracted_confidence: 0.96 },
      { name: 'pgvector / SQL', category: 'database', proficiency: 'expert', experience_years: 5, extracted_confidence: 0.94 },
      { name: 'FastAPI', category: 'backend', proficiency: 'advanced', experience_years: 4, extracted_confidence: 0.87 },
      { name: 'Scikit-learn', category: 'ai_ml', proficiency: 'advanced', experience_years: 5, extracted_confidence: 0.89 },
    ],
  }
];

export const INITIAL_GIGS: Gig[] = [
  {
    id: 'gig-201',
    title: 'Senior AI Engineer — Real-time Semantic Talent Matching System',
    client_id: 'c-301',
    client_name: 'Sarah Jenkins',
    client_company: 'Vanguard Talent Labs',
    client_avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=250',
    client_industry: 'HR Tech & AI Software',
    category: 'AI & Machine Learning',
    description: 'We are seeking a Senior AI Backend Specialist to refine our hybrid embedding and keyword search engine. The project entails implementing cosine similarity ranking over candidate embeddings, optimizing PostgreSQL RLS policies, and establishing an automated metric evaluation console (NDCG@10, MAP).',
    required_skills: ['FastAPI', 'Python', 'React', 'TypeScript', 'PostgreSQL / Supabase', 'PyTorch / NLP'],
    budget_min: 80,
    budget_max: 120,
    payment_type: 'hourly',
    work_mode: 'Remote',
    location: 'Worldwide Remote',
    application_deadline: '2026-08-15T23:59:59Z',
    posted_date: '2026-07-20T10:00:00Z',
    status: 'open',
    total_applicants: 14,
    match_breakdown: {
      overall_score: 94,
      keyword_score: 91,
      semantic_score: 97,
      skill_coverage_pct: 100,
      matching_skills: ['FastAPI', 'Python', 'React', 'TypeScript', 'PostgreSQL / Supabase', 'PyTorch / NLP'],
      missing_skills: [],
      experience_fit: 'Exact',
      justification: 'Perfect alignment across stack requirements (FastAPI, React, Supabase, PyTorch). Candidate possesses verified hybrid embedding engine implementation background.',
    },
  },
  {
    id: 'gig-202',
    title: 'Lead Frontend Engineer — High-Density Financial Dashboard',
    client_id: 'c-302',
    client_name: 'Devon Miller',
    client_company: 'Apex Trading Corp',
    client_avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=250',
    client_industry: 'FinTech & Analytics',
    category: 'Frontend Engineering',
    description: 'Build a dark-mode, command-palette driven analytical workspace for institutional traders. Requires advanced React 19, TypeScript, CSS micro-animations, and high-frequency WebSocket data grid optimization.',
    required_skills: ['React', 'TypeScript', 'Tailwind CSS', 'UI/UX Design Systems'],
    budget_min: 75,
    budget_max: 100,
    payment_type: 'hourly',
    work_mode: 'Remote',
    location: 'US East Remote',
    application_deadline: '2026-08-10T23:59:59Z',
    posted_date: '2026-07-21T11:30:00Z',
    status: 'open',
    total_applicants: 9,
    match_breakdown: {
      overall_score: 87,
      keyword_score: 85,
      semantic_score: 89,
      skill_coverage_pct: 75,
      matching_skills: ['React', 'TypeScript', 'Tailwind CSS'],
      missing_skills: ['UI/UX Design Systems'],
      experience_fit: 'Exceeds',
      justification: 'Strong React and TypeScript fluency with clean state management experience. Minor gap in dedicated UI design system portfolio.',
    },
  },
  {
    id: 'gig-203',
    title: 'FastAPI Backend Architect — Vector Search & Auth Pipeline',
    client_id: 'c-303',
    client_name: 'Elena Rostova (Client Team)',
    client_company: 'Synthetix Cloud',
    client_avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=250',
    client_industry: 'Cloud Infrastructure',
    category: 'Backend Architecture',
    description: 'Refactor core FastAPI auth routes, implement Supabase row-level security (RLS) guardrails, and audit database transaction bottlenecks under high concurrent read loads.',
    required_skills: ['FastAPI', 'Python', 'PostgreSQL / Supabase', 'Docker / CI/CD'],
    budget_min: 90,
    budget_max: 130,
    payment_type: 'hourly',
    work_mode: 'Hybrid',
    location: 'Austin, TX or Remote',
    application_deadline: '2026-08-20T23:59:59Z',
    posted_date: '2026-07-18T09:15:00Z',
    status: 'open',
    total_applicants: 6,
    match_breakdown: {
      overall_score: 91,
      keyword_score: 89,
      semantic_score: 93,
      skill_coverage_pct: 100,
      matching_skills: ['FastAPI', 'Python', 'PostgreSQL / Supabase', 'Docker / CI/CD'],
      missing_skills: [],
      experience_fit: 'Exact',
      justification: 'Comprehensive backend coverage. High confidence in FastAPI architecture and Supabase RLS security design.',
    },
  },
  {
    id: 'gig-204',
    title: 'NLP Data Scientist — Sentence-Transformers & Skill Extraction',
    client_id: 'c-304',
    client_name: 'Dr. Aris Thorne',
    client_company: 'Cognitive Science AI',
    client_avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&q=80&w=250',
    client_industry: 'Artificial Intelligence',
    category: 'Data Science & NLP',
    description: 'Train and fine-tune domain-specific HuggingFace embedding models for tech resume skill extraction and zero-shot taxonomy classification.',
    required_skills: ['Python', 'PyTorch / NLP', 'Scikit-learn', 'pgvector / SQL'],
    budget_min: 100,
    budget_max: 140,
    payment_type: 'hourly',
    work_mode: 'Remote',
    location: 'Global Remote',
    application_deadline: '2026-08-05T23:59:59Z',
    posted_date: '2026-07-22T15:45:00Z',
    status: 'open',
    total_applicants: 11,
    match_breakdown: {
      overall_score: 79,
      keyword_score: 74,
      semantic_score: 84,
      skill_coverage_pct: 50,
      matching_skills: ['Python', 'PyTorch / NLP'],
      missing_skills: ['Scikit-learn', 'pgvector / SQL'],
      experience_fit: 'Developing',
      justification: 'Strong PyTorch foundations. Secondary experience in standalone scikit-learn pipeline optimization is required for full model tuning.',
    },
  },
  {
    id: 'gig-205',
    title: 'Full-Stack React & FastAPI Engineer — Gig Marketplace Operations',
    client_id: 'c-301',
    client_name: 'Sarah Jenkins',
    client_company: 'Vanguard Talent Labs',
    client_avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=250',
    client_industry: 'HR Tech & AI Software',
    category: 'Full-Stack Engineering',
    description: 'Build complete marketplace features: candidate application management workflow, applicant status boards, proposal editing, and real-time client intake notifications.',
    required_skills: ['React', 'TypeScript', 'FastAPI', 'PostgreSQL / Supabase'],
    budget_min: 85,
    budget_max: 115,
    payment_type: 'hourly',
    work_mode: 'Remote',
    location: 'Remote',
    application_deadline: '2026-08-30T23:59:59Z',
    posted_date: '2026-07-23T08:00:00Z',
    status: 'open',
    total_applicants: 18,
    match_breakdown: {
      overall_score: 96,
      keyword_score: 95,
      semantic_score: 97,
      skill_coverage_pct: 100,
      matching_skills: ['React', 'TypeScript', 'FastAPI', 'PostgreSQL / Supabase'],
      missing_skills: [],
      experience_fit: 'Exact',
      justification: 'Ideal candidate match. Proven mastery of full-stack marketplace lifecycle from UI routing to backend DB triggers.',
    },
  }
];

export const INITIAL_APPLICATIONS: Application[] = [
  {
    id: 'app-401',
    gig_id: 'gig-201',
    gig_title: 'Senior AI Engineer — Real-time Semantic Talent Matching System',
    freelancer_id: 'f-101',
    freelancer_name: 'Elena Rostova',
    freelancer_title: 'Senior Full-Stack AI Engineer',
    freelancer_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=250',
    match_score: 94,
    keyword_score: 91,
    semantic_score: 97,
    applied_at: '2026-07-22T16:20:00Z',
    status: 'shortlisted',
    proposal_text: 'I have built multiple sentence-transformer matching pipelines integrated with Supabase pgvector and FastAPI backends. My previous platform achieved high accuracy NDCG benchmarks.',
    matching_skills: ['FastAPI', 'Python', 'React', 'TypeScript', 'PostgreSQL / Supabase', 'PyTorch / NLP'],
    missing_skills: [],
  },
  {
    id: 'app-402',
    gig_id: 'gig-201',
    gig_title: 'Senior AI Engineer — Real-time Semantic Talent Matching System',
    freelancer_id: 'f-102',
    freelancer_name: 'Marcus Vance',
    freelancer_title: 'Distributed Systems & ML Ops Engineer',
    freelancer_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=250',
    match_score: 88,
    keyword_score: 84,
    semantic_score: 92,
    applied_at: '2026-07-21T09:45:00Z',
    status: 'interview',
    proposal_text: 'Extensive background in scalable FastAPI services and Kubernetes infrastructure. Can ensure vector queries run under 50ms latency at scale.',
    matching_skills: ['FastAPI', 'Python', 'PostgreSQL / Supabase', 'Docker'],
    missing_skills: ['React', 'PyTorch / NLP'],
  },
  {
    id: 'app-403',
    gig_id: 'gig-201',
    gig_title: 'Senior AI Engineer — Real-time Semantic Talent Matching System',
    freelancer_id: 'f-104',
    freelancer_name: 'David Okafor',
    freelancer_title: 'Data Platform Engineer & Embedding Specialist',
    freelancer_avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=250',
    match_score: 82,
    keyword_score: 79,
    semantic_score: 85,
    applied_at: '2026-07-23T11:10:00Z',
    status: 'pending',
    proposal_text: 'Passionate about embedding space optimization and metric evaluation scripts (NDCG, MAP). Excited to contribute to this architecture.',
    matching_skills: ['Python', 'FastAPI', 'PostgreSQL / Supabase'],
    missing_skills: ['React', 'TypeScript'],
  },
  {
    id: 'app-404',
    gig_id: 'gig-202',
    gig_title: 'Lead Frontend Engineer — High-Density Financial Dashboard',
    freelancer_id: 'f-103',
    freelancer_name: 'Aria Chen',
    freelancer_title: 'Lead Frontend Architect & UI Systems Engineer',
    freelancer_avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=250',
    match_score: 96,
    keyword_score: 95,
    semantic_score: 97,
    applied_at: '2026-07-22T10:00:00Z',
    status: 'accepted',
    proposal_text: 'Design systems and high-density dashboard layouts are my core strength. I specialize in accessible, performance-tuned React 19 interfaces.',
    matching_skills: ['React', 'TypeScript', 'Tailwind CSS', 'UI/UX Design Systems'],
    missing_skills: [],
  }
];

export const BENCHMARK_EVALUATIONS: EvaluationBenchmark[] = [
  {
    algorithm_id: 'hybrid',
    algorithm_name: 'Hybrid AI Matching Engine (Keyword + Semantic Blend)',
    ndcg_5: 0.924,
    ndcg_10: 0.941,
    map_score: 0.896,
    mrr_score: 0.952,
    precision_5: 0.880,
    latency_ms: 42,
    total_queries_tested: 150,
    relevance_coverage: 0.985,
  },
  {
    algorithm_id: 'semantic',
    algorithm_name: 'Semantic Vector Ranker (all-MiniLM-L6-v2 Embeddings)',
    ndcg_5: 0.845,
    ndcg_10: 0.872,
    map_score: 0.810,
    mrr_score: 0.890,
    precision_5: 0.800,
    latency_ms: 38,
    total_queries_tested: 150,
    relevance_coverage: 0.940,
  },
  {
    algorithm_id: 'keyword',
    algorithm_name: 'Exact & Fuzzy Keyword Matcher (PostgreSQL tsvector)',
    ndcg_5: 0.712,
    ndcg_10: 0.748,
    map_score: 0.665,
    mrr_score: 0.780,
    precision_5: 0.640,
    latency_ms: 8,
    total_queries_tested: 150,
    relevance_coverage: 0.820,
  }
];

export const SAMPLE_RESUME_TEXT = `ELENA ROSTOVA
Senior Full-Stack AI Engineer | San Francisco, CA

SUMMARY
Accomplished software engineer with 8+ years of expertise designing intelligent Web Applications, microservices, and AI matching engines. Proven track record deploying FastAPI backend microservices, Supabase RLS authentication, and high-performance React 19 / TypeScript interfaces.

SKILLS
- Frontend: React 19, TypeScript, Next.js, Tailwind CSS, State Management
- Backend: Python, FastAPI, Node.js, REST APIs, GraphQL
- Databases: PostgreSQL, Supabase RLS, Redis, pgvector
- AI & NLP: PyTorch, HuggingFace sentence-transformers, Cosine Similarity search, Skill Extraction
- DevOps: Docker, CI/CD, GitHub Actions, AWS ECS

EXPERIENCE
Lead AI Platform Engineer — Synthetix AI (2023 - Present)
• Built hybrid candidate discovery engine matching 5,000+ technical gigs with high-precision embedding vectors.
• Implemented automated model evaluation dashboard measuring NDCG@10 and MAP metrics across query sets.

Senior Full-Stack Engineer — Cloud Matrix (2020 - 2023)
• Developed responsive React 19 SaaS dashboards with custom Tailwind CSS design system.
• Engineered secure multi-tenant Supabase database schema with strict RLS policies.`;
