import React from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const gigs = [
  { id:'atlas', title:'Rebuild client analytics portal', company:'Northstar Health', industry:'Healthcare SaaS', work:'Remote', pay:'Fixed · £7,500–£9,000', deadline:'29 Jul 2026', match:92, stage:'Open', skills:['React','FastAPI','PostgreSQL','Accessibility'], summary:'Modernise a secure reporting portal used by clinic operations teams, with clearer intake, permissions-aware dashboards, and export-ready summaries.', gaps:['HIPAA domain context'], timeline:'6–8 weeks', applicants:18 },
  { id:'ledger', title:'Payments reconciliation workflow', company:'Ledgerly', industry:'Fintech', work:'Hybrid · London', pay:'Hourly · £70–£95/hr', deadline:'02 Aug 2026', match:86, stage:'Open', skills:['Python','ETL','Supabase','Testing'], summary:'Design and implement a robust reconciliation flow for internal finance operators without adding payment custody to the product.', gaps:['Stripe Connect optional'], timeline:'4 weeks', applicants:11 },
  { id:'civic', title:'Public services case intake UI', company:'CivicWorks', industry:'GovTech', work:'Remote', pay:'Scope proposal requested', deadline:'05 Aug 2026', match:81, stage:'Open', skills:['TypeScript','Forms','Design Systems','Audit Trails'], summary:'Create a restrained, accessible case intake experience with structured version history and clear participant-visible decisions.', gaps:['Policy writing'], timeline:'Discovery + build', applicants:7 }
];
const applicants = [
  { name:'Aarav Mehta', role:'Senior full-stack engineer', location:'Bengaluru · Remote', score:94, status:'Advanced', price:'£8,400 fixed', timeline:'7 weeks', version:'Application v3', skills:['React','FastAPI','PostgreSQL','WCAG'], note:'Has shipped clinical admin workflows with audit logs and careful role boundaries.', risk:'Needs 2-day onboarding on reporting domain.' },
  { name:'Maya Thompson', role:'Frontend systems consultant', location:'Manchester · Hybrid', score:89, status:'Shortlisted', price:'£82/hr', timeline:'5 weeks', version:'Application v2', skills:['React','Design Systems','Forms','Testing'], note:'Strong UI architecture and proposal clarity; backend depth is lighter but acceptable.', risk:'Would require backend pairing for API contracts.' },
  { name:'Noah Iversen', role:'Backend product engineer', location:'Copenhagen · Remote', score:84, status:'Review', price:'£7,950 fixed', timeline:'8 weeks', version:'Application v1', skills:['Python','FastAPI','SQL','Security'], note:'Excellent backend fit with mature security thinking; frontend craft is functional.', risk:'Portfolio shows less complex dashboard polish.' }
];
const audit = ['Gig terms published · v4','Aarav submitted structured proposal · v1','Client requested clarification on rollout plan','Aarav updated proposal · v3','Client advanced applicant','Selection request sent against application v3','Freelancer accepted exact terms','Engagement workspace created'];
const nav = ['Overview','Discover','Apply','Review','Engage'];
const concepts = [
  { key:'control', title:'1. Control Room', tag:'Command-centre review', desc:'Dense but calm operations workspace for clients and expert freelancers who need fast, auditable decisions.', accent:'#1d4ed8' },
  { key:'ledger', title:'2. Ledger Board', tag:'Version-first marketplace', desc:'A document-led interface that treats every proposal, term change, and decision as a verifiable record.', accent:'#0f766e' },
  { key:'concierge', title:'3. Concierge Flow', tag:'Guided premium journey', desc:'A step-by-step experience with stronger handholding for high-stakes clients and first-time freelancers.', accent:'#7c3aed' },
  { key:'split', title:'4. Split Evidence', tag:'Comparison-first review', desc:'A two-pane marketplace pattern built around side-by-side evidence, commercial fit, and stage actions.', accent:'#b45309' },
  { key:'compact', title:'5. Compact Exchange', tag:'Responsive workspace', desc:'A lean inbox-style direction optimised for smaller screens, quick scanning, and low visual noise.', accent:'#334155' }
];

function App(){ const [concept,setConcept]=React.useState(concepts[0].key); const active=concepts.find(c=>c.key===concept); return <div className={`app theme-${concept}`} style={{'--accent':active.accent}}><Top concept={concept} setConcept={setConcept}/><main><Hero active={active}/>{concept==='control'&&<ControlRoom/>}{concept==='ledger'&&<LedgerBoard/>}{concept==='concierge'&&<ConciergeFlow/>}{concept==='split'&&<SplitEvidence/>}{concept==='compact'&&<CompactExchange/>}<RunPanel/></main></div> }
function Top({concept,setConcept}){return <header className="top"><div><b>GigMatch AI</b><span>Frontend UI/UX Concepts</span></div><nav>{concepts.map(c=><button key={c.key} onClick={()=>setConcept(c.key)} className={concept===c.key?'on':''}>{c.title.replace(/^\d\. /,'')}</button>)}</nav></header>}
function Hero({active}){return <section className="hero"><div><p>{active.tag}</p><h1>{active.title}</h1><span>{active.desc}</span></div><div className="trust"><b>Shared workflow baseline</b><small>Profile → recommended gig → match evidence → structured application → applicant review → selection request → accepted engagement.</small></div></section>}
function Pills({items}){return <div className="pills">{items.map(i=><span key={i}>{i}</span>)}</div>}
function Score({n,label='Match confidence'}){return <div className="score"><strong>{n}</strong><span>{label}</span></div>}
function Workflow({active=2}){return <ol className="workflow">{nav.map((n,i)=><li key={n} className={i<=active?'done':''}><i>{i+1}</i>{n}</li>)}</ol>}

function ControlRoom(){return <section className="grid-control"><aside className="rail"><Workflow active={3}/><div className="secure">Secure marketplace mode<br/><small>No payments, contracts, chat, or raw private text exposed.</small></div></aside><div className="panel span2"><h2>Recommended gigs</h2><div className="table">{gigs.map(g=><article key={g.id}><Score n={g.match}/><div><h3>{g.title}</h3><p>{g.company} · {g.work} · {g.pay}</p><Pills items={g.skills}/></div><button>Open terms</button></article>)}</div></div><div className="panel"><h2>Application composer</h2><label>Cover note<textarea defaultValue="I can deliver the portal rebuild with a staged rollout, accessible component system, and audited proposal checkpoints."/></label><div className="mini"><b>Bound terms</b><span>Gig v4 · Proposal v3 · Deadline {gigs[0].deadline}</span></div><button className="primary">Submit structured application</button></div><div className="panel span2"><h2>Client applicant review</h2>{applicants.map(a=><div className="applicant" key={a.name}><Score n={a.score} label={a.status}/><div><h3>{a.name}</h3><p>{a.role} · {a.price} · {a.timeline}</p><p>{a.note}</p></div><div className="actions"><button>Shortlist</button><button className="primary">Advance</button></div></div>)}</div></section>}
function LedgerBoard(){return <section className="ledger-layout"><div className="panel document"><div className="doc-head"><span>Gig terms v4</span><b>{gigs[0].title}</b></div><h2>Application-ready terms</h2><p>{gigs[0].summary}</p><dl><dt>Payment</dt><dd>{gigs[0].pay}</dd><dt>Timeline</dt><dd>{gigs[0].timeline}</dd><dt>Required evidence</dt><dd>Role-fit explanation, skill gaps, proposal version, material terms token.</dd></dl><Pills items={gigs[0].skills}/></div><div className="panel versions"><h2>Version ledger</h2>{audit.map((e,i)=><div className="event" key={e}><i>{String(i+1).padStart(2,'0')}</i><span>{e}</span></div>)}</div><div className="panel"><h2>Selection request</h2><p>Offer is bound to Aarav Mehta’s application v3. Acceptance creates a lightweight engagement workspace and unlocks consent-based contact exchange.</p><button className="primary">Accept exact terms</button><button>Request revised terms</button></div></section>}
function ConciergeFlow(){return <section className="concierge"><Workflow active={4}/><div className="card-stack"><div className="panel focus"><p>Step 3 of 5 · Review match</p><h2>{gigs[0].title}</h2><Score n={92}/><p>{gigs[0].summary}</p><div className="evidence"><div><b>Strong evidence</b><Pills items={['React portal rebuild','FastAPI APIs','Audit trails','Accessible forms']}/></div><div><b>Clarify before applying</b><Pills items={gigs[0].gaps}/></div></div></div><div className="panel side-note"><h3>Guided proposal check</h3><ul><li>Budget fits the posted fixed range.</li><li>Timeline is realistic for phased delivery.</li><li>Application will be versioned and editable.</li></ul><button className="primary">Continue to proposal</button></div></div><div className="panel calm"><h2>Engagement workspace preview</h2><p>Once exact terms are accepted, the workspace shows immutable accepted terms, lifecycle actions, activity history, and safety disclaimers—without becoming project management software.</p></div></section>}
function SplitEvidence(){const [sel,setSel]=React.useState(applicants[0]);return <section className="split-layout"><div className="panel listpane"><h2>Applicants ranked by suitability</h2>{applicants.map(a=><button key={a.name} onClick={()=>setSel(a)} className={sel.name===a.name?'selected row':'row'}><Score n={a.score} label={a.status}/><span><b>{a.name}</b><small>{a.price} · {a.version}</small></span></button>)}</div><div className="panel detailpane"><h2>{sel.name}</h2><p>{sel.role} · {sel.location}</p><div className="columns"><section><h3>Suitability evidence</h3><Pills items={sel.skills}/><p>{sel.note}</p></section><section><h3>Commercial proposal</h3><dl><dt>Price</dt><dd>{sel.price}</dd><dt>Timeline</dt><dd>{sel.timeline}</dd><dt>Risk</dt><dd>{sel.risk}</dd></dl></section></div><div className="decisionbar"><button>Ask clarification</button><button>Request revision</button><button className="primary">Send selection request</button></div></div></section>}
function CompactExchange(){return <section className="compact"><div className="phone"><div className="phonebar">GigMatch · Secure review</div>{gigs.map(g=><article key={g.id}><div><h3>{g.title}</h3><small>{g.company} · {g.pay}</small></div><Score n={g.match}/><Pills items={g.skills.slice(0,3)}/></article>)}</div><div className="panel inbox"><h2>Responsive exchange pattern</h2><p>A practical direction for mobile-first browsing and tablet review: narrow cards, sticky context, progressive disclosure, and explicit security copy.</p><div className="compact-timeline">{audit.slice(2).map(x=><span key={x}>{x}</span>)}</div><button className="primary">Open engagement workspace</button></div></section>}
function RunPanel(){return <section className="run panel"><h2>Run and view</h2><code>cd concepts-gpt-forge</code><code>npm install</code><code>npm run dev</code><p>Open the local Vite URL, usually http://localhost:5173. This concept app is standalone and uses only local mock data.</p></section>}

createRoot(document.getElementById('root')).render(<App/>);
