import { ArrowLeft, ArrowRight, Check, ChevronRight, Columns4, Grip, LockKeyhole, RotateCcw, Send, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { Link, useLocation } from "react-router-dom";
import { laneForState } from "../../domain/expansion";
import { APPLICANTS, GIGS, QA, TERMS } from "../../domain/fixtures";
import type { Role, ViewId } from "../../domain/types";
import { useConceptRoute } from "../../domain/useConceptRoute";
import "./lane.css";

const LANES=["Find","Propose","Review","Confirm","Work"] as const;

export function Lane(){const location=useLocation();const route=useConceptRoute("lane");if(location.pathname==="/lane"||location.pathname==="/lane/")return <Landing/>;return <LaneApp {...route}/>}

function Landing(){return <main id="main-content" className="ln-public"><header><Link to="/">12</Link><b>LANE</b><span>PARALLEL MARKETPLACE OPERATIONS</span></header><section>{LANES.map((lane,index)=><article key={lane} className={`is-${index}`}><span>0{index+1}</span><b>{lane}</b>{index===0&&<div><strong>03</strong><p>OPEN BRIEFS</p></div>}{index===2&&<div><strong>04</strong><p>PEOPLE IN REVIEW</p></div>}{index===3&&<div><strong>01</strong><p>EXACT DECISION</p></div>}</article>)}</section><footer><div><span>ONE BRIEF</span><h1>See every record<br/><em>where it stands.</em></h1></div><nav><Link to="/lane/freelancer/home">Specialist lanes <ArrowRight/></Link><Link to="/lane/client/home">Client lanes <ArrowRight/></Link></nav></footer></main>}

interface Props{role:Role;view:ViewId;go:(view:ViewId)=>void;switchRole:(role:Role)=>void;state:ReturnType<typeof useConceptRoute>["state"];dispatch:ReturnType<typeof useConceptRoute>["dispatch"]}

function LaneApp({role,view,go,switchRole,state,dispatch}:Props){
  const active=laneForState(state);const routes:ViewId[]=role==="client"?["home","review","candidate","selection","engagement"]:["discover","proposal","applications","selection","engagement"];
  return <div className="ln-app"><header className="ln-header"><Link to="/lane"><Columns4/>LANE <small>12</small></Link><div><button className={role==="freelancer"?"is-active":""} onClick={()=>switchRole("freelancer")}>SPECIALIST</button><button className={role==="client"?"is-active":""} onClick={()=>switchRole("client")}>CLIENT</button></div><span>TH–042 · APPLICATION v{state.applicationVersion}</span><button onClick={()=>dispatch({type:"reset"})}><RotateCcw/> RESET</button></header><nav className="ln-stage-nav">{LANES.map((lane,index)=><button className={routes[index]===view?"is-current":active===lane.toLowerCase()?"is-live":""} key={lane} onClick={()=>go(routes[index])}><span>0{index+1}</span><b>{lane}</b><small>{index===2?state.applicationStage:index===3?state.selectionStatus:index===4?state.engagementStatus.replaceAll("_"," "):role==="client"?`${APPLICANTS.length} records`:`${GIGS.length} records`}</small></button>)}</nav><main id="main-content">
    {view==="home"&&<Home go={go} state={state}/>}
    {view==="discover"&&<Discover go={go} state={state}/>}
    {view==="gig"&&<Gig go={go}/>}
    {view==="proposal"&&<Proposal go={go} state={state} dispatch={dispatch}/>}
    {view==="applications"&&<Application go={go} state={state} dispatch={dispatch}/>}
    {view==="review"&&<Review go={go} state={state}/>}
    {view==="candidate"&&<Candidate go={go} state={state} dispatch={dispatch}/>}
    {view==="selection"&&<Selection role={role} go={go} state={state} dispatch={dispatch}/>}
    {view==="engagement"&&<Engagement state={state} dispatch={dispatch}/>}
  </main><footer className="ln-footer"><Link to="/"><ArrowLeft/> Concepts</Link><span>PARALLEL RECORDS · ONE SHARED SCENARIO</span>{state.toast&&<b role="status">{state.toast}</b>}</footer></div>
}

function Home({go,state}:Pick<Props,"go"|"state">){return <section className="ln-home"><header><span>CLIENT / FULL PIPELINE</span><h1>One brief. Four records in parallel.</h1><p>Public advancement and private shortlist remain different signals.</p></header><div className="ln-board">{LANES.map((lane,index)=><section key={lane}><header><span>0{index+1}</span><b>{lane}</b></header>{index===0&&<button onClick={()=>go("review")}><strong>TH–042</strong><span>Ternary Health</span><small>14 applications</small></button>}{index===2&&APPLICANTS.slice(1).map(person=><button key={person.id} onClick={()=>go("review")}><strong>{person.match}</strong><span>{person.name}</span><small>{person.stage}</small></button>)}{index===3&&<button className="is-active" onClick={()=>go("selection")}><strong>31H</strong><span>Kavya Menon</span><small>v{state.applicationVersion} exact request</small></button>}{index===4?(state.selectionStatus==="accepted"?<button onClick={()=>go("engagement")}><Check/><span>Kavya × Ternary</span></button>:<p className="ln-empty">Awaiting an accepted exact selection.</p>):null}</section>)}</div></section>}

function Discover({go,state}:Pick<Props,"go"|"state">){return <section className="ln-discover"><header><span>SPECIALIST / PARALLEL OPPORTUNITIES</span><h1>Three briefs. Three different positions.</h1></header><div className="ln-board">{LANES.map((lane,index)=><section key={lane}><header><span>0{index+1}</span><b>{lane}</b></header>{index===0&&GIGS.slice(1).map(gig=><button key={gig.id} onClick={()=>go("gig")}><strong>{gig.match}</strong><span>{gig.company}</span><small>{gig.deadline}</small></button>)}{index===2&&<button onClick={()=>go("applications")}><strong>v{state.applicationVersion}</strong><span>Ternary Health</span><small>{state.applicationStage}</small></button>}{index===3&&<button className="is-active" onClick={()=>go("selection")}><strong>31H</strong><span>Exact selection</span><small>₹5.8L · 14 weeks</small></button>}</section>)}</div></section>}

function Gig({go}:Pick<Props,"go">){const gig=GIGS[0];return <section className="ln-detail"><header><button onClick={()=>go("discover")}><ArrowLeft/> Opportunity lanes</button><span>FIND / TH–042</span><h1>{gig.title}</h1><p>{gig.summary}</p></header><div className="ln-brief-line"><strong>92</strong><div><span>EVIDENCE FIT</span><b>{gig.matchingSkills.join(" · ")}</b></div><div><span>DISCLOSED GAP</span><b>{gig.missingSkills[0]}</b></div><div><span>TERMS</span><b>{gig.budget} · {gig.duration}</b></div></div><div className="ln-deliverables">{gig.deliverables.map((item,index)=><p key={item}><span>0{index+1}</span>{item}</p>)}</div><button className="ln-primary" onClick={()=>go("proposal")}>Move into Propose <ArrowRight/></button></section>}

function Proposal({go,state,dispatch}:Pick<Props,"go"|"state"|"dispatch">){const[note,setNote]=useState("");const invalid=note.length<24;return <section className="ln-proposal"><header><span>PROPOSE / NEW RECORD v{state.applicationVersion+1}</span><h1>Move the proposal forward with its history attached.</h1></header><form onSubmit={event=>{event.preventDefault();if(!invalid){dispatch({type:"submit-revision"});go("applications")}}}><div><label>FIXED PROPOSAL<input defaultValue="₹5,80,000"/></label><label>DELIVERY<input defaultValue="14 weeks"/></label><label>CAPACITY<input defaultValue="28 hours/week"/></label><label>REVISION NOTE<textarea value={note} onChange={event=>setNote(event.target.value)} placeholder="Explain the delivery change."/>{invalid&&<small role="alert">Add at least 24 characters.</small>}</label></div><aside><span>MOVE CONSEQUENCE</span><p>Current application</p><b>v{state.applicationVersion} / {state.applicationStage}</b><ArrowRight/><p>New application</p><b>v{state.applicationVersion+1} / Review</b><p className="is-warning">Any confirmation for v{state.applicationVersion} becomes invalid.</p><button disabled={invalid}>Move record <Send/></button></aside></form></section>}

function Application({go,state,dispatch}:Pick<Props,"go"|"state"|"dispatch">){return <section className="ln-application"><header><span>REVIEW / MY ACTIVE RECORD</span><h1>Ternary Health · application v{state.applicationVersion}</h1></header><div className="ln-record-line"><span>PROPOSAL</span><strong>{TERMS.proposal}</strong><span>STAGE</span><strong>{state.applicationStage}</strong><span>SELECTION</span><strong>{state.selectionStatus}</strong></div><section><span>STRUCTURED QUESTION</span><blockquote>{QA.question}</blockquote>{state.qaAnswered?<p>{QA.answer}</p>:<button onClick={()=>dispatch({type:"answer-qa"})}>Record answer</button>}</section><footer><button onClick={()=>go("proposal")}>Revise and return to review</button>{state.selectionStatus==="pending"&&<button onClick={()=>go("selection")}>Open Confirm lane <ArrowRight/></button>}</footer></section>}

function Review({go,state}:Pick<Props,"go"|"state">){const[stage,setStage]=useState<"all"|"review"|"advanced">("all");const people=APPLICANTS.filter(person=>stage==="all"||person.stage===(stage==="advanced"?"Advanced":"Under review"));return <section className="ln-review"><header><span>CLIENT / APPLICANT LANES</span><h1>Stage is visible. Shortlist is private.</h1><nav>{(["all","review","advanced"] as const).map(item=><button className={stage===item?"is-active":""} key={item} onClick={()=>setStage(item)}>{item}</button>)}</nav></header><div className="ln-people-lines">{people.map(person=><button key={person.id} onClick={()=>go("candidate")}><Grip/><strong>{person.match}</strong><div><b>{person.name}</b><small>{person.headline}</small></div><span>{person.availability}</span><span>{person.proposal}</span><em>{person.id==="kavya"?state.applicationStage:person.stage}</em><ChevronRight/></button>)}</div></section>}

function Candidate({go,state,dispatch}:Pick<Props,"go"|"state"|"dispatch">){const person=APPLICANTS[0];return <section className="ln-candidate"><header><button onClick={()=>go("review")}><ArrowLeft/> Applicant lanes</button><span>REVIEW / AP.001 / v{state.applicationVersion}</span><h1>{person.name}</h1><p>{person.headline}</p></header><div className="ln-candidate-line"><strong>92</strong><section><span>REVIEWED EVIDENCE</span>{person.skills.map(item=><b key={item}><Check/>{item}</b>)}</section><section><span>COMMERCIAL</span><b>{person.proposal}</b><b>{person.timeline}</b><b>{person.availability}</b></section><aside><span>GAP</span><p>{person.gap}</p></aside></div><footer><button className={state.shortlisted?"is-active":""} onClick={()=>dispatch({type:"toggle-shortlist"})}>{state.shortlisted?"✓ Private shortlist":"+ Private shortlist"}</button><button onClick={()=>dispatch({type:"toggle-advance"})}>{state.advanced?"Return to Review":"Advance"}</button><button onClick={()=>dispatch({type:"request-revision"})}>Request revision</button><button onClick={()=>go("selection")}>Move to Confirm <ArrowRight/></button></footer></section>}

function Selection({role,go,state,dispatch}:Pick<Props,"role"|"go"|"state"|"dispatch">){const[deadline,setDeadline]=useState<"24"|"48"|"72">(state.selectionDeadline);const client=role==="client";return <section className="ln-selection"><header><span>CONFIRM / ATOMIC MOVE</span><h1>{state.selectionStatus==="invalidated"?"This record moved backward.":"One move creates shared work."}</h1><p>Application v{state.applicationVersion} × gig terms v3</p></header><div className="ln-move"><section><span>FROM / CONFIRM</span><strong>{TERMS.proposal}</strong><b>{TERMS.timeline} · 28 hours/week</b><small>{state.selectionStatus.toUpperCase()}</small></section><ArrowRight/><section><span>TO / WORK</span><strong>Ternary × Kavya</strong><b>Immutable accepted terms</b><small>{state.selectionStatus==="accepted"?"CREATED":"WAITING"}</small></section></div>{state.selectionStatus==="none"&&<div className="ln-expired"><b>NO ACTIVE MOVE</b><p>The response window expired or was withdrawn. The client must place the record in Confirm again.</p></div>}{client&&state.selectionStatus!=="pending"&&<footer><label>OPEN FOR<select value={deadline} onChange={e=>setDeadline(e.target.value as "24"|"48"|"72")}><option value="24">24h</option><option value="48">48h</option><option value="72">72h</option></select></label><button onClick={()=>dispatch({type:"send-selection",deadline})}>Place in Confirm <Send/></button></footer>}{!client&&state.selectionStatus==="pending"&&<footer><p>31 hours remain. Acceptance moves this record once.</p><button onClick={()=>{dispatch({type:"accept-selection"});go("engagement")}}>Accept and move to Work <Check/></button></footer>}{state.selectionStatus==="accepted"&&<footer><p>Record moved successfully.</p><button onClick={()=>go("engagement")}>Open Work lane <ArrowRight/></button></footer>}</section>}

function Engagement({state,dispatch}:Pick<Props,"state"|"dispatch">){return <section className="ln-engagement"><header><span>WORK / ACTIVE ENGAGEMENT</span><h1>Ternary Health × Kavya Menon</h1><p>{state.engagementStatus.replaceAll("_"," ")} · accepted application v{state.applicationVersion}</p></header><div className="ln-work-line"><section><span>IMMUTABLE TERMS</span><strong>{TERMS.proposal}</strong><b>{TERMS.timeline}</b><button onClick={()=>dispatch({type:"advance-engagement"})} disabled={state.engagementStatus==="completed"}>Advance work state <ArrowRight/></button></section><aside><span>CONTACT AUTHORITY</span>{!state.contactShared||state.contactRevoked?<><LockKeyhole/><b>{state.contactRevoked?"DISPLAY STOPPED":"MASKED"}</b><button onClick={()=>dispatch({type:"share-contact"})}>Share verified email</button></>:<><ShieldCheck/><b>{state.contactRevealed?"kavya.menon@example.com":"k•••••@example.com"}</b><button onClick={()=>dispatch({type:state.contactRevealed?"revoke-contact":"reveal-contact"})}>{state.contactRevealed?"Revoke":"Reveal"}</button></>}</aside></div><div className="ln-history">{state.activity.slice(0,5).map(item=><p key={item.id}><span>{item.at}</span><b>{item.title}</b><small>{item.detail}</small></p>)}</div></section>}
