import { ArrowLeft, ArrowRight, Check, Circle, LockKeyhole, RotateCcw, Send, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { Link, useLocation } from "react-router-dom";
import { APPLICANTS, GIGS, QA, TERMS } from "../../domain/fixtures";
import type { Role, ViewId } from "../../domain/types";
import { useConceptRoute } from "../../domain/useConceptRoute";
import "./duet.css";

export function Duet() {
  const location=useLocation();const route=useConceptRoute("duet");
  if(location.pathname==="/duet"||location.pathname==="/duet/")return <DuetLanding/>;
  return <DuetApp {...route}/>;
}

function DuetLanding(){
  return <main id="main-content" className="dt-public"><header><Link to="/">07</Link><b>DUET</b><span>ONE MARKETPLACE · TWO AUTHORITIES</span><Link to="/duet/client/home">ENTER ALIGNMENT <ArrowRight/></Link></header><section><div className="dt-public-left"><span>THE SPECIALIST</span><h1>WHAT I<br/>CAN DO.</h1><p>Reviewed evidence, availability, proposal, scope, and the right to accept exact terms.</p><Link to="/duet/freelancer/home">Enter as Kavya</Link></div><i><span>92</span><b>ALIGNED</b><em/></i><div className="dt-public-right"><span>THE CLIENT</span><h1>WHAT WE<br/>NEED.</h1><p>A clear brief, accountable review, exact selection, and consent before contact.</p><Link to="/duet/client/home">Enter as Ternary</Link></div></section><footer><div>REACT · TYPESCRIPT · DESIGN SYSTEMS · WCAG</div><b>ONE DISCLOSED GAP</b><div>₹5.8L · 14 WEEKS · 28 HOURS</div></footer></main>;
}

interface DuetProps{role:Role;view:ViewId;go:(view:ViewId)=>void;switchRole:(role:Role)=>void;state:ReturnType<typeof useConceptRoute>["state"];dispatch:ReturnType<typeof useConceptRoute>["dispatch"]}

function DuetApp({role,view,go,switchRole,state,dispatch}:DuetProps){
  const nav:{v:ViewId;f:string;c:string}[]=[{v:"home",f:"Alignment",c:"Alignment"},{v:role==="client"?"review":"discover",f:"Opportunities",c:"Applicants"},{v:role==="client"?"candidate":"applications",f:"My record",c:"Dossier"},{v:"selection",f:"Exact terms",c:"Select"},{v:"engagement",f:"Shared work",c:"Shared work"}];
  return <div className={`dt-app is-${role}`}><header className="dt-header"><Link to="/duet"><b>D</b><span>DUET</span></Link><nav>{nav.map(item=><button key={item.v} className={view===item.v?"is-active":""} onClick={()=>go(item.v)}>{role==="client"?item.c:item.f}</button>)}</nav><div><button className={role==="freelancer"?"is-active":""} onClick={()=>switchRole("freelancer")}>KAVYA / F</button><button className={role==="client"?"is-active":""} onClick={()=>switchRole("client")}>TERNARY / C</button></div></header><main id="main-content">
    {view==="home"&&<DuetHome role={role} go={go} state={state}/>}
    {view==="discover"&&<DuetDiscover go={go}/>}
    {view==="gig"&&<DuetGig go={go}/>}
    {view==="proposal"&&<DuetProposal go={go} state={state} dispatch={dispatch}/>}
    {view==="applications"&&<DuetApplication go={go} state={state} dispatch={dispatch}/>}
    {view==="review"&&<DuetReview go={go} state={state}/>}
    {view==="candidate"&&<DuetCandidate go={go} state={state} dispatch={dispatch}/>}
    {view==="selection"&&<DuetSelection role={role} go={go} state={state} dispatch={dispatch}/>}
    {view==="engagement"&&<DuetEngagement state={state} dispatch={dispatch}/>}
  </main><footer className="dt-footer"><Link to="/"><ArrowLeft/> Concepts</Link><span>APPLICATION v{state.applicationVersion} / GIG v3</span><button onClick={()=>dispatch({type:"reset"})}><RotateCcw/> Reset</button></footer>{state.toast&&<div className="dt-toast" role="status">{state.toast}<Check/></div>}</div>;
}

function DuetHome({role,go,state}:Pick<DuetProps,"role"|"go"|"state">){
  return <section className="dt-home"><header><span>ACTIVE ALIGNMENT / TH–042</span><h1>{role==="client"?"One choice. Both sides visible.":"One offer. Your side stays yours."}</h1></header><div className="dt-mirror"><section><span>SPECIALIST POSITION</span><h2>Kavya Menon</h2><p>Frontend systems engineer · available 10 Aug · 28 hrs/week</p><dl><div><dt>EVIDENCE</dt><dd>92 / Strong</dd></div><div><dt>PROPOSAL</dt><dd>{TERMS.proposal}</dd></div><div><dt>RECORD</dt><dd>Application v{state.applicationVersion}</dd></div></dl></section><aside><i className="is-match"><Check/></i><span>CAPABILITY</span><i className="is-match"><Check/></i><span>CAPACITY</span><i className="is-action">!</i><span>AUTHORITY</span><b>31H</b></aside><section><span>CLIENT POSITION</span><h2>Ternary Health</h2><p>Clinical operations · fixed scope · material terms v3</p><dl><div><dt>REQUIRED</dt><dd>4 capabilities</dd></div><div><dt>BUDGET</dt><dd>₹5.2L–₹6.4L</dd></div><div><dt>REQUEST</dt><dd>Selection pending</dd></div></dl></section></div><button className="dt-center-action" onClick={()=>go("selection")}>Resolve the exact terms <ArrowRight/></button></section>;
}

function DuetDiscover({go}:Pick<DuetProps,"go">){
  const[active,setActive]=useState(0);const gig=GIGS[active];
  return <section className="dt-discover"><header><span>SPECIALIST SIDE / OPEN MARKET</span><h1>Choose which brief to answer.</h1></header><div className="dt-discovery-mirror"><section>{GIGS.map((item,index)=><button className={active===index?"is-active":""} key={item.id} onClick={()=>setActive(index)}><span>0{index+1}</span><b>{item.company}</b><small>{item.title}</small><em>{item.match}</em></button>)}</section><aside><span>ALIGNMENT</span>{gig.matchingSkills.slice(0,4).map(skill=><div key={skill}><Check/><b>{skill}</b></div>)}<div className="is-gap"><Circle/><b>{gig.missingSkills[0]}</b></div></aside><section><span>CLIENT BRIEF</span><h2>{gig.title}</h2><p>{gig.summary}</p><dl><dt>TERMS</dt><dd>{gig.budget}</dd><dt>TIME</dt><dd>{gig.duration}</dd><dt>COMMITMENT</dt><dd>{gig.commitment}</dd></dl><button onClick={()=>go("gig")}>Read both sides <ArrowRight/></button></section></div></section>;
}

function DuetGig({go}:Pick<DuetProps,"go">){
  const gig=GIGS[0];return <section className="dt-gig"><button onClick={()=>go("discover")}><ArrowLeft/> Open work</button><header><span>BRIEF / ALIGNMENT VIEW</span><h1>{gig.title}</h1></header><div className="dt-terms-mirror"><section><span>KAVYA BRINGS</span>{gig.matchingSkills.map(item=><p key={item}><Check/>{item}</p>)}<blockquote><b>DISCLOSED GAP</b>{gig.missingSkills[0]}</blockquote></section><aside><strong>92</strong><span>EVIDENCE FIT</span><i/><small>PRICE EXCLUDED</small></aside><section><span>TERNARY REQUIRES</span>{gig.requiredSkills.map(item=><p key={item}>{item}<Check/></p>)}<blockquote><b>PROJECT TERMS</b>{gig.budget} · {gig.duration}</blockquote></section></div><div className="dt-brief"><article><h2>Outcome</h2><p>{gig.summary}</p></article><article><h2>Deliverables</h2>{gig.deliverables.map((item,index)=><p key={item}><span>0{index+1}</span>{item}</p>)}</article></div><button className="dt-center-action" onClick={()=>go("proposal")}>Answer this brief <ArrowRight/></button></section>;
}

function DuetProposal({go,state,dispatch}:Pick<DuetProps,"go"|"state"|"dispatch">){
  const[workshops,setWorkshops]=useState("4");const invalid=Number(workshops)<1;
  return <section className="dt-proposal"><header><span>PROPOSAL v{state.applicationVersion} / ALIGN TERMS</span><h1>Put your answer beside their need.</h1></header><form onSubmit={e=>{e.preventDefault();if(!invalid){dispatch({type:"submit-revision"});go("applications")}}}><div className="dt-form-mirror"><section><span>YOUR PROPOSAL</span><label>Fixed amount<input defaultValue="₹5,80,000"/></label><label>Delivery<input defaultValue="14 weeks"/></label><label>Capacity<input defaultValue="28 hours/week"/></label><label>Workshops<input value={workshops} onChange={e=>setWorkshops(e.target.value)} inputMode="numeric"/>{invalid&&<small role="alert">Include at least one workshop.</small>}</label></section><aside><span>ALIGN</span>{["Within guidance","Timing fits","Capacity fits","Scope clarified"].map((item,index)=><div className={index===3&&invalid?"is-open":"is-done"} key={item}>{index===3&&invalid?"!":<Check/>}<b>{item}</b></div>)}</aside><section><span>CLIENT BRIEF</span><label>Budget guidance<b>₹5.2L–₹6.4L</b></label><label>Delivery window<b>12–16 weeks</b></label><label>Need<b>26–30 hours/week</b></label><label>Requested clarity<b>Workshop count</b></label></section></div><footer><p><LockKeyhole/> New version preserves both sides and invalidates any prior selection.</p><button disabled={invalid}>Record aligned proposal <Send/></button></footer></form></section>;
}

function DuetApplication({go,state,dispatch}:Pick<DuetProps,"go"|"state"|"dispatch">){
  return <section className="dt-application"><header><span>YOUR RECORD / APPLICATION v{state.applicationVersion}</span><h1>What changed—and what did not.</h1></header><div className="dt-version-mirror"><section><span>v1 / SUPERSEDED</span><del>{TERMS.previousProposal}</del><p>Two product-team workshops</p></section><aside><ArrowRight/><b>REVISION</b><span>26 JUL</span></aside><section><span>v{state.applicationVersion} / CURRENT</span><ins>{TERMS.proposal}</ins><p>Four product-team workshops</p></section></div><div className="dt-qa"><section><span>CLIENT QUESTION</span><blockquote>{QA.question}</blockquote></section><aside><span>Q&A</span><i/><b>ANSWERED</b></aside><section><span>YOUR ANSWER</span>{state.qaAnswered?<blockquote>{QA.answer}</blockquote>:<button onClick={()=>dispatch({type:"answer-qa"})}>Record answer</button>}</section></div><footer><button onClick={()=>go("proposal")}>Create another version</button>{state.selectionStatus==="pending"&&<button onClick={()=>go("selection")}>Review exact selection <ArrowRight/></button>}</footer></section>;
}

function DuetReview({go,state}:Pick<DuetProps,"go"|"state">){
  const[selected,setSelected]=useState(0);const person=APPLICANTS[selected];
  return <section className="dt-review"><header><span>CLIENT SIDE / FOUR PEOPLE AGAINST ONE BRIEF</span><h1>Keep the requirement fixed. Change the person.</h1></header><div className="dt-review-layout"><nav>{APPLICANTS.map((item,index)=><button key={item.id} className={selected===index?"is-active":""} onClick={()=>setSelected(index)}><strong>{item.match}</strong><span><b>{item.name}</b><small>{item.proposal} · {item.timeline}</small></span></button>)}</nav><div className="dt-mirror"><section><span>CANDIDATE POSITION</span><h2>{person.name}</h2><p>{person.note}</p><dl><div><dt>EVIDENCE</dt><dd>{person.match}</dd></div><div><dt>PROPOSAL</dt><dd>{person.proposal}</dd></div><div><dt>STAGE</dt><dd>{person.id==="kavya"?state.applicationStage:person.stage}</dd></div></dl></section><aside>{person.skills.slice(0,4).map(skill=><div key={skill}><Check/><span>{skill}</span></div>)}<div className="is-gap"><Circle/><span>1 gap</span></div></aside><section><span>FIXED CLIENT POSITION</span><h2>Ternary Health</h2><p>Accessible typed system and two clinical workflow migrations.</p><dl><div><dt>BUDGET</dt><dd>₹5.2L–₹6.4L</dd></div><div><dt>DELIVERY</dt><dd>14 weeks</dd></div><div><dt>START</dt><dd>10 Aug</dd></div></dl></section></div></div><button className="dt-center-action" onClick={()=>go("candidate")}>Open {person.name} in full <ArrowRight/></button></section>;
}

function DuetCandidate({go,state,dispatch}:Pick<DuetProps,"go"|"state"|"dispatch">){
  const person=APPLICANTS[0];return <section className="dt-candidate"><button onClick={()=>go("review")}><ArrowLeft/> Applicant comparison</button><header><span>FULL ALIGNMENT / APPLICATION v{state.applicationVersion}</span><h1>Kavya × Ternary</h1></header><div className="dt-mirror dt-candidate-mirror"><section><span>KAVYA / SPECIALIST</span><h2>{person.proposal}</h2><p>{person.note}</p>{person.skills.map(skill=><div key={skill}><Check/>{skill}</div>)}</section><aside><strong>92</strong><span>ALIGNED</span><div><b>CAPABILITY</b><Check/></div><div><b>TIME</b><Check/></div><div><b>SCOPE</b><Check/></div><div className="is-gap"><b>DOMAIN</b><Circle/></div></aside><section><span>TERNARY / CLIENT</span><h2>₹5.2L–₹6.4L</h2><p>Clinical operations brief v3 · 14 weeks · 26–30 hours/week.</p>{GIGS[0].requiredSkills.map(skill=><div key={skill}>{skill}<Check/></div>)}</section></div><p className="dt-gap">ONE DISCLOSED GAP · {person.gap}</p><footer><button className={state.shortlisted?"is-active":""} onClick={()=>dispatch({type:"toggle-shortlist"})}>{state.shortlisted?"✓ Private shortlist":"+ Private shortlist"}</button><button onClick={()=>dispatch({type:"toggle-advance"})}>{state.advanced?"Return to review":"Advance"}</button><button onClick={()=>go("selection")}>Move both sides to exact terms <ArrowRight/></button></footer></section>;
}

function DuetSelection({role,go,state,dispatch}:Pick<DuetProps,"role"|"go"|"state"|"dispatch">){
  const[deadline,setDeadline]=useState<"24"|"48"|"72">(state.selectionDeadline);const client=role==="client";
  return <section className="dt-selection"><header><span>FINAL ALIGNMENT / APPLICATION v{state.applicationVersion}</span><h1>Both sides, one exact center.</h1></header><div className="dt-exact-mirror"><section><span>SPECIALIST ACCEPTS</span><h2>{TERMS.proposal}</h2><p>{TERMS.timeline} · {TERMS.availability}</p>{TERMS.included.map(item=><p key={item}><Check/>{item}</p>)}</section><aside><ShieldCheck/><span>EXACT</span><b>v{state.applicationVersion} × v3</b><i/><small>{state.selectionStatus.toUpperCase()}</small></aside><section><span>CLIENT CONFIRMS</span><h2>{TERMS.proposal}</h2><p>14 weeks · 28 hours/week</p>{TERMS.included.map(item=><p key={item}>{item}<Check/></p>)}</section></div>{client&&state.selectionStatus!=="pending"&&<footer><label>OPEN FOR<select value={deadline} onChange={e=>setDeadline(e.target.value as "24"|"48"|"72")}><option value="24">24h</option><option value="48">48h</option><option value="72">72h</option></select></label><button onClick={()=>dispatch({type:"send-selection",deadline})}>Send aligned terms <Send/></button></footer>}{!client&&state.selectionStatus==="pending"&&<footer><p>31 hours remain · a revision separates the sides again.</p><button onClick={()=>{dispatch({type:"accept-selection"});go("engagement")}}>Accept exact center <Check/></button></footer>}{state.selectionStatus==="accepted"&&<footer><p>Both authorities confirmed.</p><button onClick={()=>go("engagement")}>Enter shared work <ArrowRight/></button></footer>}</section>;
}

function DuetEngagement({state,dispatch}:Pick<DuetProps,"state"|"dispatch">){
  return <section className="dt-engagement"><header><span>SHARED CENTER / ENGAGEMENT</span><h1>Ternary × Kavya</h1><p>{state.engagementStatus.replace("_"," ")} · application v{state.applicationVersion} · gig v3</p></header><div className="dt-shared"><section><span>THE SPECIALIST</span><h2>Kavya Menon</h2><p>28 hours/week · starts 10 Aug</p></section><aside><ShieldCheck/><span>SHARED TERMS</span><strong>{TERMS.proposal}</strong><b>{TERMS.timeline}</b><button onClick={()=>dispatch({type:"advance-engagement"})} disabled={state.engagementStatus==="completed"}>Advance shared state</button></aside><section><span>THE CLIENT</span><h2>Ternary Health</h2><p>Clinical Trial Operations · terms v3</p></section></div><div className="dt-contact"><section><span>CONTACT PERMISSION</span>{!state.contactShared||state.contactRevoked?<><LockKeyhole/><b>{state.contactRevoked?"DISPLAY STOPPED":"PRIVATE"}</b><button onClick={()=>dispatch({type:"share-contact"})}>Share verified email</button></>:<><ShieldCheck/><b>{state.contactRevealed?"kavya.menon@example.com":"k•••••@example.com"}</b><button onClick={()=>dispatch({type:state.contactRevealed?"revoke-contact":"reveal-contact"})}>{state.contactRevealed?"Stop sharing":"Reveal"}</button></>}</section></div></section>;
}
