import { ArrowLeft, ArrowRight, Check, Command as CommandIcon, CornerDownLeft, FileClock, LockKeyhole, RotateCcw, Search, Send, ShieldCheck, Slash, Terminal, X } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { Link, useLocation, useNavigate } from "react-router-dom";
import { COMMANDS, resolveCommand } from "../../domain/expansion";
import { APPLICANTS, GIGS, QA, TERMS } from "../../domain/fixtures";
import type { Role, ViewId } from "../../domain/types";
import { useConceptRoute } from "../../domain/useConceptRoute";
import "./command.css";

export function Command(){const location=useLocation();const route=useConceptRoute("command");if(location.pathname==="/command"||location.pathname==="/command/")return <Landing/>;return <CommandApp {...route}/>}

function Landing(){return <main id="main-content" className="cm-public"><header><Link to="/">13</Link><b>COMMAND</b><span>GIGMATCH AI / DIRECT PROFESSIONAL WORKSPACE</span></header><section><span>TYPE THE INTENT. KEEP THE CONTEXT.</span><h1>The marketplace<br/>at your <em>command.</em></h1><p>Navigate records, compare evidence, revise terms, and exercise authority through one calm, searchable interface.</p><div className="cm-demo"><Slash/><span>compare applicants</span><CornerDownLeft/></div><nav><Link to="/command/freelancer/home">Open specialist workspace <ArrowRight/></Link><Link to="/command/client/home">Open client workspace <ArrowRight/></Link></nav></section><footer>{COMMANDS.slice(0,4).map((item,index)=><span key={item.input}><b>⌘{index+1}</b>{item.input}</span>)}</footer></main>}

interface Props{role:Role;view:ViewId;go:(view:ViewId)=>void;switchRole:(role:Role)=>void;state:ReturnType<typeof useConceptRoute>["state"];dispatch:ReturnType<typeof useConceptRoute>["dispatch"]}

function CommandApp({role,view,go,switchRole,state,dispatch}:Props){
  const[input,setInput]=useState("");const[notice,setNotice]=useState("Ready");const field=useRef<HTMLInputElement>(null);const navigate=useNavigate();
  useEffect(()=>{function focus(event:KeyboardEvent){if(event.key==="/"&&document.activeElement?.tagName!=="INPUT"&&document.activeElement?.tagName!=="TEXTAREA"){event.preventDefault();field.current?.focus()}}window.addEventListener("keydown",focus);return()=>window.removeEventListener("keydown",focus)},[]);
  function run(raw=input){const result=resolveCommand(raw);if(result.kind==="route"){if(result.role&&result.role!==role){dispatch({type:"set-role",role:result.role});navigate(`/command/${result.role}/${result.view}`)}else go(result.view);setNotice(`Opened: ${result.label}`)}else if(result.kind==="role"){switchRole(result.role);setNotice(`Switched to ${result.role}`)}else if(result.kind==="reset"){dispatch({type:"reset"});setNotice("Scenario reset")}else setNotice(`No command found for “${raw}”. Try a suggested action.`);setInput("")}
  return <div className="cm-app"><header className="cm-header"><Link to="/command"><CommandIcon/>COMMAND <small>13</small></Link><form onSubmit={event=>{event.preventDefault();run()}}><Search/><input ref={field} value={input} onChange={event=>setInput(event.target.value)} placeholder="Type a command or press /" aria-label="Command input"/><kbd>/</kbd><button aria-label="Run command"><CornerDownLeft/></button></form><div><button className={role==="freelancer"?"is-active":""} onClick={()=>switchRole("freelancer")}>F</button><button className={role==="client"?"is-active":""} onClick={()=>switchRole("client")}>C</button></div></header><aside className="cm-rail"><div><span>ACTIVE ENTITY</span><b>TH–042</b><small>Ternary Health</small></div><nav>{[
    ["home","Home"],[role==="client"?"review":"discover",role==="client"?"Applicants":"Market"],[role==="client"?"candidate":"applications","Record"],["selection","Selection"],["engagement","Engagement"]
  ].map(item=><button key={item[0]} className={view===item[0]?"is-active":""} onClick={()=>go(item[0] as ViewId)}><span>›</span>{item[1]}</button>)}</nav><div className="cm-authority"><span>AUTHORITY</span><b>{role==="client"?"Issue selection":"Accept exact terms"}</b><small>{state.selectionStatus}</small></div><Link to="/"><ArrowLeft/> Concepts</Link></aside><main id="main-content">
    <div className="cm-context"><span>role:{role}</span><span>view:{view}</span><span>application:v{state.applicationVersion}</span><span>status:{state.applicationStage.toLowerCase().replaceAll(" ","_")}</span></div>
    {view==="home"&&<Home role={role} go={go} state={state}/>}
    {view==="discover"&&<Discover go={go}/>}
    {view==="gig"&&<Gig go={go}/>}
    {view==="proposal"&&<Proposal go={go} state={state} dispatch={dispatch}/>}
    {view==="applications"&&<Application go={go} state={state} dispatch={dispatch}/>}
    {view==="review"&&<Review go={go} state={state}/>}
    {view==="candidate"&&<Candidate go={go} state={state} dispatch={dispatch}/>}
    {view==="selection"&&<Selection role={role} go={go} state={state} dispatch={dispatch}/>}
    {view==="engagement"&&<Engagement state={state} dispatch={dispatch}/>}
  </main><footer className="cm-footer"><span><i/> {notice}</span><button onClick={()=>dispatch({type:"reset"})}><RotateCcw/> reset scenario</button><span>LOCAL / NO NETWORK</span></footer>{state.toast&&<div className="cm-toast" role="status">{state.toast}</div>}
    <div className="cm-suggestions" aria-label="Suggested commands">{COMMANDS.slice(0,3).map(item=><button key={item.input} onClick={()=>{setInput(item.input);run(item.input)}}><Terminal/>{item.input}</button>)}</div>
  </div>
}

function Home({role,go,state}:Pick<Props,"role"|"go"|"state">){return <section className="cm-home"><header><span>workspace.open / TH–042</span><h1>{role==="client"?"Four applicants. One unresolved authority.":"One exact request is waiting."}</h1><p>Use the visible actions or type the same intent in the command bar.</p></header><div className="cm-action-list"><button onClick={()=>go(role==="client"?"review":"discover")}><span>01</span><div><b>{role==="client"?"compare applicants":"open market"}</b><small>{role==="client"?"Review four normalized records":"Three evidence-matched opportunities"}</small></div><ArrowRight/></button><button onClick={()=>go(role==="client"?"candidate":"applications")}><span>02</span><div><b>{role==="client"?"open kavya":"open application"}</b><small>Application v{state.applicationVersion} · {state.applicationStage}</small></div><ArrowRight/></button><button className="is-authority" onClick={()=>go("selection")}><span>03</span><div><b>review selection</b><small>{TERMS.proposal} · 31 hours remain</small></div><ArrowRight/></button></div></section>}

function Discover({go}:Pick<Props,"go">){const[selected,setSelected]=useState(0);const gig=GIGS[selected];return <section className="cm-discover"><header><span>market.query / evidence_fit desc</span><h1>Three opportunity records.</h1></header><div className="cm-query-grid"><nav>{GIGS.map((item,index)=><button className={selected===index?"is-active":""} onClick={()=>setSelected(index)} key={item.id}><span>{item.match}</span><b>{item.company}</b><small>{item.paymentType} · {item.deadline}</small></button>)}</nav><article><span>ENTITY / GIG</span><h2>{gig.title}</h2><p>{gig.summary}</p><dl><div><dt>evidence_fit</dt><dd>{gig.match}</dd></div><div><dt>commercial</dt><dd>{gig.budget}</dd></div><div><dt>capacity</dt><dd>{gig.commitment}</dd></div></dl><p className="cm-gap"><X/> {gig.missingSkills[0]}</p><button onClick={()=>go("gig")}>open {gig.company.toLowerCase()} <ArrowRight/></button></article></div></section>}

function Gig({go}:Pick<Props,"go">){const gig=GIGS[0];return <section className="cm-entity"><header><button onClick={()=>go("discover")}><ArrowLeft/> market.query</button><span>entity.gig / TH–042 / terms:v3</span><h1>{gig.title}</h1><p>{gig.summary}</p></header><div className="cm-properties"><section><span>REQUIRED</span>{gig.requiredSkills.map(item=><p key={item}><Check/>{item}</p>)}</section><section><span>DELIVERABLES</span>{gig.deliverables.map((item,index)=><p key={item}><b>0{index+1}</b>{item}</p>)}</section><aside><span>MATERIAL TERMS</span><strong>{gig.budget}</strong><b>{gig.duration}</b><b>{gig.commitment}</b><small>Closes {gig.deadline}</small></aside></div><button className="cm-primary" onClick={()=>go("proposal")}>revise proposal <ArrowRight/></button></section>}

function Proposal({go,state,dispatch}:Pick<Props,"go"|"state"|"dispatch">){const[note,setNote]=useState("");const invalid=note.length<24;return <section className="cm-proposal"><header><span>action.revise / application:v{state.applicationVersion}</span><h1>Write the next immutable version.</h1></header><form onSubmit={event=>{event.preventDefault();if(!invalid){dispatch({type:"submit-revision"});go("applications")}}}><div><label>proposal.fixed<input defaultValue="₹5,80,000"/></label><label>delivery.weeks<input defaultValue="14"/></label><label>capacity.weekly<input defaultValue="28 hours"/></label><label>revision.reason<textarea value={note} onChange={event=>setNote(event.target.value)} placeholder="Describe the changed delivery commitment."/>{invalid&&<small role="alert">Enter at least 24 characters.</small>}</label></div><aside><FileClock/><span>RESULT</span><b>application v{state.applicationVersion+1}</b><p>Selection for v{state.applicationVersion} → invalidated</p><button disabled={invalid}>execute revision <Send/></button></aside></form></section>}

function Application({go,state,dispatch}:Pick<Props,"go"|"state"|"dispatch">){return <section className="cm-application"><header><span>entity.application / AP.001 / v{state.applicationVersion}</span><h1>Kavya → Ternary</h1></header><div className="cm-properties"><section><span>PROPOSAL</span><strong>{TERMS.proposal}</strong><p>{TERMS.timeline}<br/>{TERMS.availability}</p><button onClick={()=>go("proposal")}>revise proposal</button></section><section><span>STRUCTURED Q&A</span><blockquote>{QA.question}</blockquote>{state.qaAnswered?<p>{QA.answer}</p>:<button onClick={()=>dispatch({type:"answer-qa"})}>answer question</button>}</section><aside><span>STATE</span><strong>{state.applicationStage}</strong><b>selection:{state.selectionStatus}</b>{state.selectionStatus==="pending"&&<button onClick={()=>go("selection")}>review selection</button>}</aside></div></section>}

function Review({go,state}:Pick<Props,"go"|"state">){const[selected,setSelected]=useState(0);return <section className="cm-review"><header><span>compare.applicants / sort:evidence_fit</span><h1>Applicant result set.</h1></header><div className="cm-result-table"><header><b>#</b><b>APPLICANT</b><b>EVIDENCE</b><b>AVAILABILITY</b><b>PROPOSAL</b><b>STAGE</b></header>{APPLICANTS.map((person,index)=><button className={selected===index?"is-active":""} key={person.id} onClick={()=>setSelected(index)} onDoubleClick={()=>go("candidate")}><span>0{index+1}</span><b>{person.name}</b><strong>{person.match}</strong><span>{person.availability}</span><span>{person.proposal}</span><em>{person.id==="kavya"?state.applicationStage:person.stage}</em></button>)}</div><footer><span>selected:{APPLICANTS[selected].id}</span><button onClick={()=>go("candidate")}>open selected <ArrowRight/></button></footer></section>}

function Candidate({go,state,dispatch}:Pick<Props,"go"|"state"|"dispatch">){const person=APPLICANTS[0];return <section className="cm-candidate"><header><button onClick={()=>go("review")}><ArrowLeft/> compare.applicants</button><span>entity.applicant / kavya_menon / v{state.applicationVersion}</span><h1>{person.name}</h1><p>{person.headline}</p></header><div className="cm-properties"><section><span>EVIDENCE / 92</span>{person.skills.map(item=><p key={item}><Check/>{item}</p>)}</section><section><span>PROPOSAL</span><strong>{person.proposal}</strong><p>{person.timeline}<br/>{person.availability}</p><small>Commercial value excluded from fit.</small></section><aside><span>DISCLOSED GAP</span><p>{person.gap}</p></aside></div><footer className="cm-actions"><button onClick={()=>dispatch({type:"toggle-shortlist"})}>{state.shortlisted?"remove shortlist":"add shortlist"}</button><button onClick={()=>dispatch({type:"toggle-advance"})}>{state.advanced?"return review":"advance applicant"}</button><button onClick={()=>dispatch({type:"request-revision"})}>request revision</button><button onClick={()=>go("selection")}>review selection <ArrowRight/></button></footer></section>}

function Selection({role,go,state,dispatch}:Pick<Props,"role"|"go"|"state"|"dispatch">){const[deadline,setDeadline]=useState<"24"|"48"|"72">(state.selectionDeadline);const client=role==="client";return <section className="cm-selection"><header><span>action.selection / authority:{role}</span><h1>Confirm the exact record.</h1><p>Changing application v{state.applicationVersion} invalidates this command.</p></header><div className="cm-execution"><header><ShieldCheck/><b>selection.execute</b><span>{state.selectionStatus}</span></header><p><span>gig</span><b>TH–042 / terms v3</b></p><p><span>application</span><b>AP.001 / v{state.applicationVersion}</b></p><p><span>proposal</span><b>{TERMS.proposal}</b></p><p><span>delivery</span><b>{TERMS.timeline} / 28 hours/week</b></p></div>{state.selectionStatus==="none"&&<div className="cm-expired"><b>selection.active:false</b><p>The previous request expired or was withdrawn. Run a fresh client request.</p></div>}{client&&state.selectionStatus!=="pending"&&<footer><label>deadline<select value={deadline} onChange={event=>setDeadline(event.target.value as "24"|"48"|"72")}><option value="24">24h</option><option value="48">48h</option><option value="72">72h</option></select></label><button onClick={()=>dispatch({type:"send-selection",deadline})}>execute request <Send/></button></footer>}{!client&&state.selectionStatus==="pending"&&<footer><p>31 hours remain.</p><button onClick={()=>{dispatch({type:"accept-selection"});go("engagement")}}>execute acceptance <Check/></button></footer>}{state.selectionStatus==="accepted"&&<footer><p>engagement.created:true</p><button onClick={()=>go("engagement")}>open engagement <ArrowRight/></button></footer>}</section>}

function Engagement({state,dispatch}:Pick<Props,"state"|"dispatch">){return <section className="cm-engagement"><header><span>entity.engagement / EN.001</span><h1>Ternary × Kavya</h1><p>status:{state.engagementStatus} / application:v{state.applicationVersion} / terms:v3</p></header><div className="cm-properties"><section><span>IMMUTABLE TERMS</span><strong>{TERMS.proposal}</strong><p>{TERMS.timeline} · 28 hours/week</p><button onClick={()=>dispatch({type:"advance-engagement"})} disabled={state.engagementStatus==="completed"}>advance engagement</button></section><section><span>ACTIVITY</span>{state.activity.slice(0,4).map(item=><p key={item.id}><b>{item.title}</b><small>{item.at}</small></p>)}</section><aside><span>CONTACT.PERMISSION</span>{!state.contactShared||state.contactRevoked?<><LockKeyhole/><strong>masked</strong><button onClick={()=>dispatch({type:"share-contact"})}>share contact</button></>:<><ShieldCheck/><strong>{state.contactRevealed?"kavya.menon@example.com":"k•••••@example.com"}</strong><button onClick={()=>dispatch({type:state.contactRevealed?"revoke-contact":"reveal-contact"})}>{state.contactRevealed?"revoke display":"reveal contact"}</button></>}</aside></div></section>}
