import type { Applicant, Gig } from "./types";

export const GIGS: Gig[] = [
  {
    id: "ternary-clinical",
    title: "Senior Frontend Systems Engineer for Clinical Trial Operations",
    company: "Ternary Health",
    category: "Frontend systems",
    summary:
      "Unify three clinical-trial operations products around an accessible React system, establish typed workflow patterns, and migrate the highest-risk investigator journeys.",
    workMode: "Remote",
    location: "India · overlap with CET",
    posted: "24 Jul 2026",
    deadline: "07 Aug · 18:00 IST",
    duration: "14 weeks",
    commitment: "26–30 hours / week",
    paymentType: "fixed",
    budget: "₹5.2L–₹6.4L fixed",
    requiredSkills: ["React", "TypeScript", "Design systems", "WCAG 2.2"],
    preferredSkills: ["Regulated software", "Storybook"],
    deliverables: [
      "Audited component and workflow inventory",
      "Accessible typed component system",
      "Migration of investigator setup and trial-status workflows",
      "Adoption guidance for the internal product team",
    ],
    match: 92,
    matchLabel: "Strong evidence fit",
    matchReason:
      "Your reviewed work covers all four required capabilities. Regulated-health experience is adjacent rather than direct and is treated as a disclosed gap.",
    matchingSkills: ["React", "TypeScript", "Design systems", "WCAG 2.2", "Storybook"],
    missingSkills: ["Direct clinical-trial domain work"],
    applicants: 14,
  },
  {
    id: "meridian-platform",
    title: "Frontend Platform Lead for Audit-grade Reporting",
    company: "Meridian Ledger",
    category: "Platform engineering",
    summary:
      "Create typed reporting primitives and performance budgets for a financial compliance workspace used by distributed analyst teams.",
    workMode: "Remote",
    location: "Asia time zones",
    posted: "23 Jul 2026",
    deadline: "11 Aug · 20:00 IST",
    duration: "4 months",
    commitment: "20–24 hours / week",
    paymentType: "hourly",
    budget: "₹3,200–₹4,100 / hour",
    requiredSkills: ["React", "TypeScript", "Testing", "Web performance"],
    preferredSkills: ["OpenAPI", "Playwright"],
    deliverables: ["Typed reporting primitives", "Performance-budget CI", "Adoption playbook"],
    match: 86,
    matchLabel: "Good evidence fit",
    matchReason: "Strong platform and test experience; limited explicit evidence for OpenAPI generation.",
    matchingSkills: ["React", "TypeScript", "Testing", "Playwright"],
    missingSkills: ["OpenAPI generation"],
    applicants: 19,
  },
  {
    id: "common-ground",
    title: "Accessible Public-service Portal Audit",
    company: "Common Ground Digital",
    category: "Accessibility",
    summary:
      "Audit a multilingual public-service portal and deliver a prioritized remediation plan with representative frontend fixes.",
    workMode: "Remote",
    location: "Worldwide",
    posted: "21 Jul 2026",
    deadline: "04 Aug · 23:59 IST",
    duration: "4–6 weeks",
    commitment: "Flexible",
    paymentType: "open",
    budget: "Open to scoped proposals",
    requiredSkills: ["WCAG", "React", "Accessibility testing"],
    preferredSkills: ["Public sector", "Screen readers"],
    deliverables: ["Accessibility audit", "Remediation backlog", "Representative fixes"],
    match: 81,
    matchLabel: "Promising evidence fit",
    matchReason: "Core accessibility requirements are covered; no public-sector case study is attached.",
    matchingSkills: ["WCAG", "React", "Accessibility testing", "Screen readers"],
    missingSkills: ["Public-sector delivery"],
    applicants: 8,
  },
];

export const APPLICANTS: Applicant[] = [
  {
    id: "kavya",
    name: "Kavya Menon",
    initials: "KM",
    headline: "Frontend systems engineer · accessibility and design systems",
    location: "Kochi · UTC+5:30",
    experience: "8 years",
    availability: "10 Aug · 28 hrs/week",
    match: 92,
    proposal: "₹5.8L fixed",
    timeline: "14 weeks",
    version: 2,
    stage: "Advanced",
    shortlisted: true,
    skills: ["React", "TypeScript", "Design systems", "WCAG 2.2", "Storybook"],
    gap: "Regulated-health work is adjacent; no direct clinical-trial project is listed.",
    note: "I would begin with workflow and component inventory, then migrate the highest-risk investigator journeys alongside your product team.",
  },
  {
    id: "dev",
    name: "Dev Malhotra",
    initials: "DM",
    headline: "Staff frontend engineer · platform modernization",
    location: "Delhi · UTC+5:30",
    experience: "10 years",
    availability: "18 Aug · 30 hrs/week",
    match: 87,
    proposal: "₹6.2L fixed",
    timeline: "12–14 weeks",
    version: 1,
    stage: "Under review",
    shortlisted: false,
    skills: ["React", "TypeScript", "Platform architecture", "Testing"],
    gap: "No explicit screen-reader testing evidence.",
    note: "My recent work consolidated four product surfaces and introduced typed migration tooling.",
  },
  {
    id: "sana",
    name: "Sana Iqbal",
    initials: "SI",
    headline: "Accessibility lead and product engineer",
    location: "Hyderabad · UTC+5:30",
    experience: "7 years",
    availability: "Immediate · 24 hrs/week",
    match: 84,
    proposal: "₹5.5L fixed",
    timeline: "16 weeks",
    version: 3,
    stage: "Under review",
    shortlisted: false,
    skills: ["WCAG 2.2", "React", "Screen readers", "Storybook"],
    gap: "Less evidence of large TypeScript migrations.",
    note: "I can establish the accessibility baseline and pair with engineers through migration.",
  },
  {
    id: "rohan",
    name: "Rohan Batra",
    initials: "RB",
    headline: "Clinical software UI engineer",
    location: "Pune · UTC+5:30",
    experience: "6 years",
    availability: "14 Aug · 20 hrs/week",
    match: 79,
    proposal: "₹4.9L fixed",
    timeline: "18 weeks",
    version: 1,
    stage: "Advanced",
    shortlisted: false,
    skills: ["React", "Clinical software", "TypeScript", "Validation"],
    gap: "Limited evidence of design-system ownership.",
    note: "I bring direct clinical operations context and can support validation documentation.",
  },
];

export const QA = {
  question: "How will you validate keyboard and screen-reader behavior during the first migration?",
  answer:
    "I’ll establish a representative workflow matrix in week one, combine automated checks with NVDA and VoiceOver passes, and record exceptions with owners before migration begins.",
  requestedChange: "Clarify the number of product-team workshops included in the fixed proposal.",
};

export const TERMS = {
  proposal: "₹5.8L fixed",
  previousProposal: "₹5.6L fixed",
  timeline: "14 weeks",
  availability: "10 Aug 2026 · 28 hours/week",
  included: [
    "Component and workflow inventory",
    "Accessible React component system",
    "Two high-risk workflow migrations",
    "Four product-team workshops",
  ],
  excluded: ["Backend API redesign", "Clinical validation ownership", "Ongoing maintenance after handoff"],
  assumptions: ["Existing product engineers support integration", "Ternary supplies access to representative test accounts"],
};

export const BASE_ACTIVITY = [
  {
    id: "a1",
    at: "27 Jul · 16:42",
    title: "Fresh selection request sent",
    detail: "Application v2 · gig terms v3 · expires in 48 hours.",
    actor: "client" as const,
  },
  {
    id: "a2",
    at: "27 Jul · 14:08",
    title: "Application version 2 submitted",
    detail: "Four product-team workshops clarified; previous request invalidated.",
    actor: "freelancer" as const,
  },
  {
    id: "a3",
    at: "26 Jul · 18:20",
    title: "Proposal revision requested",
    detail: "Client requested workshop scope clarification.",
    actor: "client" as const,
  },
  {
    id: "a4",
    at: "26 Jul · 11:35",
    title: "Applicant advanced",
    detail: "Participant-visible stage changed from Under review to Advanced.",
    actor: "client" as const,
  },
  {
    id: "a5",
    at: "25 Jul · 17:04",
    title: "Added to private shortlist",
    detail: "Client-only review state. The applicant was not notified.",
    actor: "client" as const,
  },
];
