import { ArrowLeft, ArrowRight, Check, ChevronLeft, ChevronRight, DoorOpen, FileText, LockKeyhole, RotateCcw, Send, ShieldCheck, Ticket, X } from "lucide-react";
import { useState } from "react";
import { Link, useLocation } from "react-router-dom";
import { artifactCoverage, EVIDENCE_ARTIFACTS } from "../../domain/expansion";
import { APPLICANTS, GIGS, QA, TERMS } from "../../domain/fixtures";
import type { Role, ViewId } from "../../domain/types";
import { useConceptRoute } from "../../domain/useConceptRoute";
import "./proofroom.css";

export function Proofroom(){const location=useLocation();const route=useConceptRoute("proofroom");if(location.pathname==="/proofroom"||location.pathname==="/proofroom/")return <Landing/>;return <ProofroomApp {...route}/>}

function Landing(){return <main id="main-content" className="pr-public"><header><Link to="/">14 / INDEX</Link><b>PROOFROOM</b><span>GIGMATCH AI · REVIEWED WORK, CURATED</span></header><section><div><span>ENTER THROUGH THE EVIDENCE</span><h1>Claims stay outside.<br/><em>Proof enters the room.</em></h1><p>A marketplace where requirements meet reviewed work artifacts before proposals, price, or persuasion.</p><nav><Link to="/proofroom/freelancer/home">Enter specialist rooms <DoorOpen/></Link><Link to="/proofroom/client/home">Enter client rooms <DoorOpen/></Link></nav></div><aside>{EVIDENCE_ARTIFACTS.map((item,index)=><article key={item.id} className={index===4?"is-gap":""}><span>ROOM {item.room}</span><b>{item.title}</b><small>{item.kind}</small></article>)}</aside></section><footer><span>5 ARTIFACTS</span><b>4 REQUIREMENTS COVERED</b><span>1 ABSENCE DISCLOSED</span></footer></main>}

interface Props{role:Role;view:ViewId;go:(view:ViewId)=>void;switchRole:(role:Role)=>void;state:ReturnType<typeof useConceptRoute>["state"];dispatch:ReturnType<typeof useConceptRoute>["dispatch"]}

function ProofroomApp({role,view,go,switchRole,state,dispatch}:Props){
  const rooms:{v:ViewId;f:string;c:string}[]=[{v:"home",f:"Foyer",c:"Foyer"},{v:role==="client"?"review":"discover",f:"Brief room",c:"Applicant rooms"},{v:role==="client"?"candidate":"applications",f:"My collection",c:"Kavya collection"},{v:"selection",f:"Private room",c:"Private room"},{v:"engagement",f:"Shared archive",c:"Shared archive"}];
  return <div className="pr-app"><header className="pr-header"><Link to="/proofroom"><DoorOpen/>PROOFROOM <small>14</small></Link><nav>{rooms.map((item,index)=><button className={view===item.v?"is-active":""} onClick={()=>go(item.v)} key={item.v}><span>0{index+1}</span>{role==="client"?item.c:item.f}</button>)}</nav><div><button className={role==="freelancer"?"is-active":""} onClick={()=>switchRole("freelancer")}>SPECIALIST</button><button className={role==="client"?"is-active":""} onClick={()=>switchRole("client")}>CLIENT</button></div></header><main id="main-content">
    {view==="home"&&<Home role={role} go={go} state={state}/>}
    {view==="discover"&&<Discover go={go}/>}
    {view==="gig"&&<Gig go={go}/>}
    {view==="proposal"&&<Proposal go={go} state={state} dispatch={dispatch}/>}
    {view==="applications"&&<Application go={go} state={state} dispatch={dispatch}/>}
    {view==="review"&&<Review go={go} state={state}/>}
    {view==="candidate"&&<Candidate go={go} state={state} dispatch={dispatch}/>}
    {view==="selection"&&<Selection role={role} go={go} state={state} dispatch={dispatch}/>}
    {view==="engagement"&&<Engagement state={state} dispatch={dispatch}/>}
  </main><footer className="pr-footer"><Link to="/"><ArrowLeft/> Fifteen concepts</Link><span>COLLECTION TH–042 · APPLICATION v{state.applicationVersion}</span><button onClick={()=>dispatch({type:"reset"})}><RotateCcw/> Reset collection</button></footer>{state.toast&&<div className="pr-toast" role="status"><Check/>{state.toast}</div>}</div>
}

function Home({role,go,state}:Pick<Props,"role"|"go"|"state">){return <section className="pr-home"><header><span>FOYER / COLLECTION TH–042</span><h1>{role==="client"?"Four collections await examination.":"Your reviewed work has a visitor."}</h1><p>{role==="client"?"The brief remains fixed while each applicant’s artifacts rotate through the rooms.":"Ternary Health has issued an exact request against application v"+state.applicationVersion+"."}</p></header><div className="pr-foyer"><article><span>NOW SHOWING</span><strong>92</strong><h2>{role==="client"?"Kavya Menon":"Ternary Health"}</h2><p>{role==="client"?"Five reviewed evidence artifacts":"Senior Frontend Systems Engineer"}</p><button onClick={()=>go(role==="client"?"candidate":"discover")}>Enter collection <ArrowRight/></button></article><aside>{EVIDENCE_ARTIFACTS.map(item=><p key={item.id}><span>{item.room}</span><b>{item.title}</b><small>{item.kind}</small></p>)}</aside></div><button className="pr-private-invite" onClick={()=>go("selection")}><Ticket/><span>PRIVATE ROOM INVITATION</span><b>Exact terms · 31 hours remain</b><ArrowRight/></button></section>}

function Discover({go}:Pick<Props,"go">){const[active,setActive]=useState(0);const gig=GIGS[active];return <section className="pr-discover"><header><span>BRIEF ROOM / OPEN COLLECTIONS</span><h1>Begin with the requirement label.</h1></header><div className="pr-wall"><nav>{GIGS.map((item,index)=><button className={active===index?"is-active":""} key={item.id} onClick={()=>setActive(index)}><span>0{index+1}</span><b>{item.company}</b><small>{item.title}</small></button>)}</nav><article><span>CURATOR’S LABEL / {gig.matchLabel}</span><strong>{gig.match}</strong><h2>{gig.title}</h2><p>{gig.matchReason}</p><div>{gig.requiredSkills.map(skill=><b key={skill}>{skill}</b>)}</div><button onClick={()=>go("gig")}>Enter this brief room <ArrowRight/></button></article></div></section>}

function Gig({go}:Pick<Props,"go">){const gig=GIGS[0];const coverage=artifactCoverage(gig.requiredSkills);return <section className="pr-gig"><header><button onClick={()=>go("discover")}><ArrowLeft/> Open collections</button><span>BRIEF ROOM / TH–042 / TERMS v3</span><h1>{gig.title}</h1><p>{gig.summary}</p></header><div className="pr-coverage">{coverage.map((item,index)=><article key={item.skill}><span>WALL 0{index+1}</span><Check/><h2>{item.skill}</h2><p>{item.artifact}</p><small>REVIEWED CONNECTION</small></article>)}<article className="is-absence"><span>WALL 05</span><X/><h2>Clinical-trial domain</h2><p>No direct artifact claimed</p><small>DISCLOSED ABSENCE</small></article></div><div className="pr-terms"><span>MATERIAL TERMS</span><b>{gig.budget}</b><b>{gig.duration}</b><b>{gig.commitment}</b><button onClick={()=>go("proposal")}>Curate proposal evidence <ArrowRight/></button></div></section>}

function Proposal({go,state,dispatch}:Pick<Props,"go"|"state"|"dispatch">){const[selected,setSelected]=useState<string[]>(["system","migration","access","workshops"]);const invalid=selected.length<4;function toggle(id:string){setSelected(items=>items.includes(id)?items.filter(item=>item!==id):[...items,id])}return <section className="pr-proposal"><header><span>CURATION DESK / APPLICATION v{state.applicationVersion+1}</span><h1>Pair every promise with reviewed work.</h1><p>Keep all four reviewed artifacts paired. The disclosed absence cannot be presented as evidence.</p></header><form onSubmit={event=>{event.preventDefault();if(!invalid){dispatch({type:"submit-revision"});go("applications")}}}><div className="pr-artifact-picker">{EVIDENCE_ARTIFACTS.map(item=><button type="button" disabled={item.id==="gap"} className={selected.includes(item.id)?"is-selected":item.id==="gap"?"is-gap":""} onClick={()=>toggle(item.id)} key={item.id}><span>ROOM {item.room}</span><FileText/><b>{item.title}</b><small>{item.kind}</small>{selected.includes(item.id)&&<Check/>}</button>)}</div><div className="pr-pairs">{GIGS[0].deliverables.map((deliverable,index)=><label key={deliverable}><span>PROMISE 0{index+1}</span><b>{deliverable}</b><select aria-label={`Evidence for ${deliverable}`} defaultValue={EVIDENCE_ARTIFACTS[index].id}>{EVIDENCE_ARTIFACTS.slice(0,4).filter(item=>selected.includes(item.id)).map(item=><option value={item.id} key={item.id}>{item.title}</option>)}</select></label>)}</div><section><label>FIXED PROPOSAL<input defaultValue="₹5,80,000"/></label><label>DELIVERY<input defaultValue="14 weeks"/></label><label>CAPACITY<input defaultValue="28 hours/week"/></label><p>{selected.length} artifacts attached · application v{state.applicationVersion+1}</p><button disabled={invalid}>Record curated proposal <Send/></button></section></form></section>}

function Application({go,state,dispatch}:Pick<Props,"go"|"state"|"dispatch">){return <section className="pr-application"><header><span>MY COLLECTION / APPLICATION v{state.applicationVersion}</span><h1>Evidence, terms, and clarification in one catalogue.</h1></header><div className="pr-catalogue">{EVIDENCE_ARTIFACTS.map(item=><article key={item.id} className={item.id==="gap"?"is-gap":""}><span>{item.room}</span><h2>{item.title}</h2><p>{item.note}</p><small>{item.kind}</small></article>)}</div><section className="pr-qa"><span>STRUCTURED Q&A</span><blockquote>{QA.question}</blockquote>{state.qaAnswered?<p>{QA.answer}</p>:<button onClick={()=>dispatch({type:"answer-qa"})}>Add answer to catalogue</button>}</section><footer><button onClick={()=>go("proposal")}>Recurate proposal</button>{state.selectionStatus==="pending"&&<button onClick={()=>go("selection")}>Enter private room <ArrowRight/></button>}</footer></section>}

function Review({go,state}:Pick<Props,"go"|"state">){const[selected,setSelected]=useState(0);const person=APPLICANTS[selected];function move(by:number){setSelected(current=>(current+by+APPLICANTS.length)%APPLICANTS.length)}return <section className="pr-review"><header><span>APPLICANT ROOMS / FIXED BRIEF TH–042</span><h1>Rotate the collection, not the requirement.</h1></header><div className="pr-rotator"><button aria-label="Previous collection" onClick={()=>move(-1)}><ChevronLeft/></button><article><span>COLLECTION 0{selected+1} / APPLICATION v{person.id==="kavya"?state.applicationVersion:person.version}</span><strong>{person.match}</strong><h2>{person.name}</h2><p>{person.headline}</p><div>{person.skills.map(skill=><b key={skill}>{skill}</b>)}</div><blockquote>{person.gap}</blockquote><button onClick={()=>go("candidate")}>Enter full collection <DoorOpen/></button></article><button aria-label="Next collection" onClick={()=>move(1)}><ChevronRight/></button></div><footer>{APPLICANTS.map((item,index)=><button className={index===selected?"is-active":""} key={item.id} onClick={()=>setSelected(index)}>0{index+1} / {item.name}</button>)}</footer></section>}

function Candidate({go,state,dispatch}:Pick<Props,"go"|"state"|"dispatch">){const person=APPLICANTS[0];return <section className="pr-candidate"><header><button onClick={()=>go("review")}><ArrowLeft/> Applicant rooms</button><span>KAVYA COLLECTION / AP.001 / v{state.applicationVersion}</span><h1>{person.name}</h1><p>{person.headline}</p></header><div className="pr-catalogue">{EVIDENCE_ARTIFACTS.map(item=><article key={item.id} className={item.id==="gap"?"is-gap":""}><span>{item.room}</span><h2>{item.title}</h2><p>{item.note}</p><small>{item.id==="gap"?person.gap:item.proves.join(" · ")}</small></article>)}</div><div className="pr-commercial"><span>COMMERCIAL LABEL / SEPARATE FROM EVIDENCE</span><strong>{person.proposal}</strong><b>{person.timeline}</b><b>{person.availability}</b></div><footer><button className={state.shortlisted?"is-active":""} onClick={()=>dispatch({type:"toggle-shortlist"})}>{state.shortlisted?"✓ Private shortlist":"+ Private shortlist"}</button><button onClick={()=>dispatch({type:"toggle-advance"})}>{state.advanced?"Return to review":"Advance"}</button><button onClick={()=>dispatch({type:"request-revision"})}>Request revision</button><button onClick={()=>go("selection")}>Invite to private room <ArrowRight/></button></footer></section>}

function Selection({role,go,state,dispatch}:Pick<Props,"role"|"go"|"state"|"dispatch">){const[deadline,setDeadline]=useState<"24"|"48"|"72">(state.selectionDeadline);const client=role==="client";return <section className="pr-selection"><header><LockKeyhole/><span>PRIVATE ROOM / EXACT AUTHORITY</span><h1>Only the decision enters.</h1><p>Application v{state.applicationVersion} · gig terms v3 · evidence coverage and disclosed absence preserved.</p></header><div className="pr-private-sheet"><section><span>EXACT TERMS</span><strong>{TERMS.proposal}</strong><b>{TERMS.timeline} · 28 hours/week</b><small>Application v{state.applicationVersion} × Gig v3</small></section><section><span>EVIDENCE COVERAGE</span><strong>4 / 4</strong><b>React · TypeScript · Design systems · WCAG</b><small>Commercial terms excluded from coverage.</small></section><section className="is-gap"><span>DISCLOSED ABSENCE</span><strong>01</strong><b>Direct clinical-trial work</b><small>No claim substituted.</small></section></div>{state.selectionStatus==="none"&&<div className="pr-expired"><b>PRIVATE ROOM CLOSED</b><p>The invitation expired or was withdrawn. The client must open a fresh exact-version room.</p></div>}{client&&state.selectionStatus!=="pending"&&<footer><label>ROOM OPEN FOR<select value={deadline} onChange={e=>setDeadline(e.target.value as "24"|"48"|"72")}><option value="24">24 hours</option><option value="48">48 hours</option><option value="72">72 hours</option></select></label><button onClick={()=>dispatch({type:"send-selection",deadline})}>Send private invitation <Send/></button></footer>}{!client&&state.selectionStatus==="pending"&&<footer><p>31 hours remain. Acceptance creates the shared archive.</p><button onClick={()=>{dispatch({type:"accept-selection"});go("engagement")}}>Accept exact record <Check/></button></footer>}{state.selectionStatus==="accepted"&&<footer><p>Private decision recorded.</p><button onClick={()=>go("engagement")}>Enter shared archive <ArrowRight/></button></footer>}</section>}

function Engagement({state,dispatch}:Pick<Props,"state"|"dispatch">){return <section className="pr-engagement"><header><span>SHARED ARCHIVE / EN.001</span><h1>Accepted proof. Preserved terms.</h1><p>Ternary Health × Kavya Menon · {state.engagementStatus.replaceAll("_"," ")}</p></header><div className="pr-archive"><section><span>ACCEPTED CATALOGUE</span>{EVIDENCE_ARTIFACTS.slice(0,4).map(item=><p key={item.id}><b>{item.room}</b><span>{item.title}</span><small>{item.kind}</small></p>)}<button onClick={()=>dispatch({type:"advance-engagement"})} disabled={state.engagementStatus==="completed"}>Advance archive state <ArrowRight/></button></section><aside><span>CONTACT / CONSENT EXHIBIT</span>{!state.contactShared||state.contactRevoked?<><LockKeyhole/><strong>{state.contactRevoked?"DISPLAY STOPPED":"MASKED"}</strong><p>Contact remains outside the archive until consent.</p><button onClick={()=>dispatch({type:"share-contact"})}>Share verified email</button></>:<><ShieldCheck/><strong>{state.contactRevealed?"kavya.menon@example.com":"k•••••@example.com"}</strong><button onClick={()=>dispatch({type:state.contactRevealed?"revoke-contact":"reveal-contact"})}>{state.contactRevealed?"Stop display":"Authorize reveal"}</button></>}</aside></div></section>}
