import type { Applicant, ConceptMeta, Gig } from "./types";

export const CONCEPTS: ConceptMeta[] = [
  {
    id: "concierge",
    number: "01",
    name: "Concierge",
    thesis: "Guided, calm, next-action service",
    interaction: "One consequential decision at a time",
  },
  {
    id: "ledger",
    number: "02",
    name: "Terms Ledger",
    thesis: "Commercial clarity and version trust",
    interaction: "A durable record, not a dashboard",
  },
  {
    id: "exchange",
    number: "03",
    name: "The Exchange",
    thesis: "Search-led professional marketplace",
    interaction: "Compare opportunities before opening a brief",
  },
  {
    id: "workroom",
    number: "04",
    name: "Deal Room",
    thesis: "Shared case workspace for a single decision",
    interaction: "People, evidence, terms and history in context",
  },
  {
    id: "pocket",
    number: "05",
    name: "Pocket Desk",
    thesis: "Mobile-first, interruption-resilient workflow",
    interaction: "Fast review with deliberate action sheets",
  },
  {
    id: "studio",
    number: "06",
    name: "Studio",
    thesis: "A human, image-led marketplace with cultural confidence",
    interaction: "Editorial stories, bold art direction, and work shown at full scale",
  },
  {
    id: "signal-index",
    number: "07",
    name: "Signal Index",
    thesis: "A vivid modernist catalogue built for fast visual comparison",
    interaction: "Poster-scale typography and a colour-coded evidence grid",
  },
  {
    id: "afterdark",
    number: "08",
    name: "Afterdark",
    thesis: "A cinematic private network for senior independent talent",
    interaction: "Immersive dossiers, restrained luxury, and focused decisions",
  },
];

export const GIGS: Gig[] = [
  {
    id: "gig-northstar",
    title: "Senior Design Systems Engineer for Clinical Operations",
    company: "Northstar Health Systems",
    companySummary: "Healthcare software team modernising tools used by hospital operations staff.",
    category: "Frontend engineering",
    location: "India",
    workMode: "Remote",
    posted: "22 Jul 2026",
    deadline: "06 Aug 2026 · 6:00 PM IST",
    duration: "12–16 weeks",
    weeklyCommitment: "25–30 hours / week",
    budget: "₹4.8L–₹6.2L",
    paymentStructure: "Fixed price",
    summary:
      "Consolidate three clinician-facing React products into one accessible component system, document adoption patterns, and migrate the highest-use workflows.",
    deliverables: [
      "Audited component inventory and migration map",
      "Accessible React component library with documented patterns",
      "Migration of appointment and care-plan workflows",
    ],
    requiredSkills: ["React", "TypeScript", "Design systems", "WCAG 2.2"],
    preferredSkills: ["Storybook", "Healthcare UX"],
    match: 88,
    matchLabel: "Strong match",
    matchingSkills: ["React", "TypeScript", "Design systems", "Storybook"],
    missingSkills: ["Healthcare UX"],
    matchReason:
      "Your reviewed profile covers all four required engineering capabilities. Healthcare domain experience is preferred, not required.",
    applicants: 12,
  },
  {
    id: "gig-grain",
    title: "Frontend Platform Engineer for B2B Workflow Suite",
    company: "Grainline Software",
    companySummary: "Bootstrapped B2B software company serving logistics teams across South Asia.",
    category: "Platform engineering",
    location: "Asia time zones",
    workMode: "Remote",
    posted: "21 Jul 2026",
    deadline: "09 Aug 2026 · 8:00 PM IST",
    duration: "4 months",
    weeklyCommitment: "20–25 hours / week",
    budget: "₹2,800–₹3,600 / hour",
    paymentStructure: "Hourly",
    summary:
      "Improve frontend platform reliability, introduce typed API boundaries, and establish performance budgets across a large React application.",
    deliverables: ["Typed API client layer", "Performance-budget CI checks", "Frontend reliability playbook"],
    requiredSkills: ["React", "TypeScript", "Testing", "Web performance"],
    preferredSkills: ["Playwright", "OpenAPI"],
    match: 82,
    matchLabel: "Good match",
    matchingSkills: ["React", "TypeScript", "Testing", "Playwright"],
    missingSkills: ["OpenAPI"],
    matchReason:
      "Your platform and testing experience aligns closely. The profile has limited explicit evidence for OpenAPI contract generation.",
    applicants: 18,
  },
  {
    id: "gig-prism",
    title: "Accessible Product UI Audit and Remediation Plan",
    company: "Prism Civic Labs",
    companySummary: "Civic technology studio building public-service applications.",
    category: "Product accessibility",
    location: "Worldwide",
    workMode: "Remote",
    posted: "19 Jul 2026",
    deadline: "02 Aug 2026 · 11:59 PM IST",
    duration: "3–5 weeks",
    weeklyCommitment: "Flexible",
    budget: "₹1.6L maximum guidance",
    paymentStructure: "Open to proposals",
    summary:
      "Audit a production civic-services portal, prioritise WCAG issues, and provide a practical remediation plan with representative fixes.",
    deliverables: ["Accessibility audit", "Prioritised remediation backlog", "Representative React fixes"],
    requiredSkills: ["WCAG", "React", "Accessibility testing"],
    preferredSkills: ["Civic technology", "Screen readers"],
    match: 76,
    matchLabel: "Promising match",
    matchingSkills: ["React", "WCAG", "Accessibility testing"],
    missingSkills: ["Civic technology"],
    matchReason:
      "Core accessibility requirements are covered. No reviewed civic-technology case study is currently attached to your profile.",
    applicants: 7,
  },
];

export const APPLICANTS: Applicant[] = [
  {
    id: "app-meera",
    name: "Meera Shah",
    initials: "MS",
    headline: "Design systems engineer · React and accessibility",
    location: "Pune · UTC+5:30",
    experience: "8 years",
    availability: "From 10 Aug · 28 hrs/week",
    match: 91,
    proposal: "₹5.6L fixed",
    timeline: "14 weeks",
    version: 2,
    coverNote:
      "I have led two multi-product design-system migrations and can begin with the clinical workflow inventory before component consolidation.",
    skills: ["React", "TypeScript", "Storybook", "WCAG 2.2"],
    gap: "Healthcare domain is adjacent rather than direct.",
    stage: "Advanced",
    shortlisted: true,
  },
  {
    id: "app-arjun",
    name: "Arjun Rao",
    initials: "AR",
    headline: "Senior frontend platform engineer",
    location: "Bengaluru · UTC+5:30",
    experience: "9 years",
    availability: "From 18 Aug · 30 hrs/week",
    match: 86,
    proposal: "₹6.0L fixed",
    timeline: "12–14 weeks",
    version: 1,
    coverNote:
      "My recent work focused on component adoption tooling, typed migrations, and performance budgets across four React products.",
    skills: ["React", "TypeScript", "Design systems", "Testing"],
    gap: "No explicit screen-reader testing evidence.",
    stage: "Under review",
    shortlisted: false,
  },
  {
    id: "app-nila",
    name: "Nila Fernandez",
    initials: "NF",
    headline: "Accessibility specialist and frontend lead",
    location: "Kochi · UTC+5:30",
    experience: "7 years",
    availability: "Immediate · 24 hrs/week",
    match: 84,
    proposal: "₹5.2L fixed",
    timeline: "16 weeks",
    version: 3,
    coverNote:
      "I can lead the accessibility baseline and pair with your product engineers on migration, documentation, and adoption.",
    skills: ["WCAG 2.2", "React", "Screen readers", "Storybook"],
    gap: "Less evidence of large-scale TypeScript migration.",
    stage: "Under review",
    shortlisted: false,
  },
];

export const ACTIVITY = [
  ["24 Jul · 10:42", "Application version 2 submitted", "Commercial proposal updated from ₹5.4L to ₹5.6L."],
  ["23 Jul · 16:10", "Advanced to next stage", "Northstar Health Systems notified Meera."],
  ["23 Jul · 11:26", "Added to internal shortlist", "Private client action; applicant was not notified."],
  ["22 Jul · 19:04", "Application submitted", "Version 1 responded to gig terms version 3."],
];
