"""Internal matching contracts, builders, and scoring/preparation utilities."""

from app.matching.builders import build_freelancer_match_profile, build_gig_match_profile
from app.matching.contracts import (
    ExplanationReason,
    ExplanationReasonCode,
    FreelancerMatchProfile,
    GigMatchProfile,
    MatchExplanation,
    NormalizedSkill,
    ScoreExplanation,
    SkillEvidence,
    SkillGapSeverity,
    SkillGapSummary,
)
from app.matching.data_access import (
    AuthContext,
    ClientGigMatchingData,
    ClientOwnedGigsData,
    ForbiddenRoleError,
    FreelancerMatchingData,
    MatchingRepository,
    MissingProfileError,
    ResourceNotFoundError,
    ResourceOwnershipError,
    UnsupportedRoleError,
    authenticate_matching_request,
    prepare_client_gig_matching_data,
    prepare_client_owned_gig_profiles,
    prepare_freelancer_matching_data,
)
from app.matching.hybrid import (
    HybridMatchResult,
    HybridRankingConfig,
    HybridScoreBreakdown,
    combine_hybrid_score,
    rank_freelancers_for_gig_hybrid,
    rank_gigs_for_freelancer_hybrid,
    score_hybrid_match,
)
from app.matching.keyword import (
    KeywordMatchResult,
    KeywordScoreBreakdown,
    rank_freelancers_for_gig,
    rank_gigs_for_freelancer,
    score_keyword_match,
)
from app.matching.semantic import (
    DeterministicFakeEmbeddingProvider,
    EmbeddingProvider,
    SentenceTransformerEmbeddingProvider,
    build_freelancer_embedding_text,
    build_gig_embedding_text,
    cosine_similarity,
)
from app.matching.semantic_ranker import (
    SemanticMatchResult,
    SemanticScoreBreakdown,
    rank_freelancers_for_gig_semantic,
    rank_gigs_for_freelancer_semantic,
    score_semantic_match,
)

__all__ = [
    "FreelancerMatchProfile",
    "GigMatchProfile",
    "AuthContext",
    "ClientGigMatchingData",
    "ClientOwnedGigsData",
    "ExplanationReason",
    "ExplanationReasonCode",
    "ForbiddenRoleError",
    "FreelancerMatchingData",
    "HybridMatchResult",
    "HybridRankingConfig",
    "HybridScoreBreakdown",
    "KeywordMatchResult",
    "KeywordScoreBreakdown",
    "MatchingRepository",
    "MatchExplanation",
    "MissingProfileError",
    "NormalizedSkill",
    "ResourceNotFoundError",
    "ResourceOwnershipError",
    "SemanticMatchResult",
    "SemanticScoreBreakdown",
    "ScoreExplanation",
    "SkillEvidence",
    "SkillGapSeverity",
    "SkillGapSummary",
    "UnsupportedRoleError",
    "DeterministicFakeEmbeddingProvider",
    "EmbeddingProvider",
    "SentenceTransformerEmbeddingProvider",
    "authenticate_matching_request",
    "build_freelancer_match_profile",
    "build_freelancer_embedding_text",
    "build_gig_match_profile",
    "build_gig_embedding_text",
    "combine_hybrid_score",
    "cosine_similarity",
    "prepare_client_gig_matching_data",
    "prepare_client_owned_gig_profiles",
    "prepare_freelancer_matching_data",
    "rank_freelancers_for_gig",
    "rank_freelancers_for_gig_hybrid",
    "rank_freelancers_for_gig_semantic",
    "rank_gigs_for_freelancer",
    "rank_gigs_for_freelancer_hybrid",
    "rank_gigs_for_freelancer_semantic",
    "score_hybrid_match",
    "score_keyword_match",
    "score_semantic_match",
]
